In [1]:
# libraries
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)
import seaborn as sns

import time
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')
import warnings
warnings.filterwarnings('ignore')
warnings.filterwarnings(action="ignore", module="sklearn", message="^n_iter")

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from catboost import CatBoostClassifier
from sklearn.utils import resample
from sklearn.feature_selection import chi2, f_classif, mutual_info_classif, RFECV, SelectKBest, SelectFromModel
from sklearn.metrics import accuracy_score, classification_report, roc_curve, auc, confusion_matrix, log_loss, f1_score
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
from sklearn.model_selection import train_test_split, KFold

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, cross_val_score, cross_validate, learning_curve

In [2]:
data = pd.read_csv("data.csv")
data.drop("Unnamed: 0", axis = 1, inplace = True)

In [3]:
cat_target = data["default"]
cat_features = data.drop("default", axis = 1)
X_trainC, X_testC, Y_trainC, Y_testC = train_test_split(cat_features, cat_target, test_size=0.3, random_state = 42)

In [7]:
# Upsampling for imbalance
def binary_upsample(data, label):
    value_count = data[label].value_counts()
    frqs = data[label].value_counts().values
    idc = data[label].value_counts().index
    minorfrq = value_count[frqs == min(frqs)].index[0] 
    n_sample = max(frqs) - min(frqs)
    minorindex = data[label][data[label] == minorfrq].index.values
    resampled = resample(minorindex, n_samples = n_sample)
    _ = pd.DataFrame(list(data.index) + list(resampled), columns =["Index"])
    balanced = pd.merge(_, data, how ="left", left_on= "Index", right_on= data.index)
    return balanced

In [ ]:
# Dummify
dummed_data = pd.get_dummies(data, drop_first = True)
updsampled = binary_upsample(dummed_data, "default").reindex()
updsampled.drop("Index", axis = 1, inplace = True)

In [ ]:
target = updsampled["default"]
features = updsampled.drop("default", axis = 1)
X_train, X_test, Y_train, Y_test = train_test_split(features, target, test_size=0.3, random_state = 42)

In [ ]:
Y_train.mean()
Y_test.mean()

### Ramdon Forest

In [64]:
# Setup 
KF = KFold(3, shuffle = True, random_state= 42)
def RF(X, Y, X1, Y1, params):
    start = time.time()
    RF = RandomForestClassifier(n_jobs = -1, oob_score = True,random_state = 42, class_weight= "balanced", 
                                n_estimators = params[0],
                                min_samples_split = params[1],
                                min_samples_leaf = params[2],
                                max_samples = params[3],
                                max_leaf_nodes = params[4],
                                max_depth = params[5]).fit(X,Y)
    stop = time.time()
    Time = stop - start
    TrainCV = cross_val_score(RF, X, Y, cv=KF, scoring = "f1", n_jobs = -1)
    train_F1Score = f1_score(Y, RF.predict(X))
    train_ac = RF.score(X, Y)
    Train_CM = confusion_matrix(Y, RF.predict(X))
    
    TestCV = cross_val_score(RF, X1, Y1, cv=KF, scoring = "f1", n_jobs = -1)
    test_F1Score = f1_score(Y1, RF.predict(X1))
    tes_ac = RF.score(X1, Y1) 
    Test_CM = confusion_matrix(Y1, RF.predict(X1))
    
    return TrainCV, train_F1Score , train_ac, Train_CM, TestCV, test_F1Score, tes_ac, Test_CM, Time

In [80]:
# Ramdonized Search
pipeline = Pipeline([("EF",RandomForestClassifier(n_jobs = -1, oob_score = True, 
                                                  random_state = 42, class_weight= "balanced"))])
param_grid = {
                  "EF__max_depth": [10, 50, 100, 150, 200, 250], 
                  "EF__max_samples": [0.2, 0.4, 0.6, 0.8],
                  "EF__min_samples_leaf": [10, 50, 100], 
                  "EF__min_samples_split": [10, 50, 100],
                  "EF__n_estimators" : [50, 100, 200, 400, 1000],
                  "EF__max_leaf_nodes" : [10, 20, 50, 100]
    
                  }                                               
# pipeline.get_params().keys()
search = RandomizedSearchCV(
    estimator = pipeline,
    param_distributions = param_grid,
    n_iter = 100, 
    return_train_score = True,
    n_jobs= -1,
    scoring="f1",
    cv = 5,
    verbose=3)
  
search = search.fit(X_train, Y_train) 
print(search.best_params_, search.best_score_)

Fitting 5 folds for each of 100 candidates, totalling 500 fits
{'EF__n_estimators': 100, 'EF__min_samples_split': 50, 'EF__min_samples_leaf': 100, 'EF__max_samples': 0.2, 'EF__max_leaf_nodes': 100, 'EF__max_depth': 200} 0.6478119837534354


In [79]:
RF(X_train, Y_train, X_test, Y_test, [100, 2, 2, 0.2, 5, 10])

(array([0.63220935, 0.63254681, 0.62926675]),
 0.6323907117285774,
 0.6414857428393883,
 array([[51998, 25856],
        [30107, 48136]]),
 array([0.62176795, 0.63018992, 0.63271393]),
 0.6321031678937579,
 0.642221856828951,
 array([[22402, 11242],
        [12693, 20562]]),
 4.838979721069336)

In [51]:
# Ramdonized Search
pipeline = Pipeline([('selector', SelectKBest(chi2)),
                     ("EF",RandomForestClassifier(n_jobs = -1, oob_score = True, random_state = 42,  class_weight= "balanced",))])
param_grid = {
                  "EF__max_depth": [3, 5, 10, 15, 20], 
                  "EF__max_samples": [0.1, 0.2, 0.3, 0.4],
                  "EF__min_samples_leaf": [2, 4 ,8], 
                  "EF__min_samples_split": [2, 4 ,8],
                  "EF__n_estimators" : [20, 40, 80, 100],
                  "EF__max_features" : [2 , 4, 6, 10, 15, 20, 25],
                  "EF__max_leaf_nodes" : [5, 10, 15, 20],
                  "selector__k": range(50, 150, 10)
                  }                                               
# pipeline.get_params().keys()
search = RandomizedSearchCV(
    estimator = pipeline,
    param_distributions = param_grid,
    n_iter = 50, 
    return_train_score = True,
    n_jobs= -1,
    scoring="f1",
    cv = 5,
    verbose=3)

search = search.fit(X_train, Y_train)
print(search.best_params_, search.best_score_)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
{'selector__k': 140, 'EF__n_estimators': 20, 'EF__min_samples_split': 8, 'EF__min_samples_leaf': 8, 'EF__max_samples': 0.1, 'EF__max_leaf_nodes': 5, 'EF__max_features': 6, 'EF__max_depth': 20} 0.6486812440819931


In [53]:
chi_train = SelectKBest(chi2, k = 140).fit_transform(X_train, Y_train)
chi_test = SelectKBest(chi2, k = 140).fit_transform(X_test, Y_test)
RF(chi_train, Y_train, chi_test, Y_test, [20, 8, 8, 0.1, 5, 6, 20])

(array([0.64942974, 0.6597975 , 0.64534117]),
 0.6470162838831949,
 0.6372768214635771,
 array([[47585, 30269],
        [26351, 51892]]),
 array([0.61600262, 0.63768784, 0.6319706 ]),
 0.6513624642832253,
 0.6261080135726992,
 array([[18520, 15124],
        [ 9889, 23366]]),
 1.0207369327545166)

In [2]:
47585/(47585+30269)

0.6112081588614586

In [54]:
# Ramdonized Search
pipeline = Pipeline([('selector', SelectKBest(f_classif)),
                     ("EF",RandomForestClassifier(n_jobs = -1, oob_score = True, random_state = 42,  class_weight= "balanced"))])
param_grid = {
                  "EF__max_depth": [3, 5, 10, 15, 20], 
                  "EF__max_samples": [0.1, 0.2, 0.3, 0.4],
                  "EF__min_samples_leaf": [2, 4 ,8], 
                  "EF__min_samples_split": [2, 4 ,8],
                  "EF__n_estimators" : [20, 40, 80, 100, 120],
                  "EF__max_features" : [2 , 4, 6, 10, 15, 20, 25],
                  "EF__max_leaf_nodes" : [5, 10, 15, 20],
                  "selector__k": range(50, 150, 10)
                  }                                               
# pipeline.get_params().keys()
search = RandomizedSearchCV(
    estimator = pipeline,
    param_distributions = param_grid,
    n_iter = 50, 
    return_train_score = True,
    n_jobs= -1,
    scoring="f1",
    cv = 5,
    verbose=3)

search = search.fit(X_train, Y_train)
print(search.best_params_, search.best_score_)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
{'selector__k': 140, 'EF__n_estimators': 40, 'EF__min_samples_split': 4, 'EF__min_samples_leaf': 4, 'EF__max_samples': 0.2, 'EF__max_leaf_nodes': 15, 'EF__max_features': 6, 'EF__max_depth': 10} 0.640545694817667


In [56]:
f_train = SelectKBest(f_classif, k = 140).fit_transform(X_train, Y_train)
f_test = SelectKBest(f_classif, k = 140).fit_transform(X_test, Y_test)
RF(f_train, Y_train, f_test, Y_test, [40, 4, 4, 0.2, 15, 6, 10])

(array([0.6419609 , 0.64820115, 0.63761377]),
 0.6455754538786584,
 0.6501982741500477,
 array([[51765, 26089],
        [28514, 49729]]),
 array([0.62933009, 0.64583236, 0.6340309 ]),
 0.6003692348267564,
 0.6376029537063335,
 array([[24444,  9200],
        [15044, 18211]]),
 2.0121419429779053)

In [57]:
# Ramdonized Search
pipeline = Pipeline([('selector', SelectKBest(mutual_info_classif)),
                     ("EF",RandomForestClassifier(n_jobs = -1, oob_score = True, random_state = 42,  class_weight= "balanced"))])
param_grid = {
                  "EF__max_depth": [3, 5, 10, 15, 20], 
                  "EF__max_samples": [0.1, 0.2, 0.3, 0.4],
                  "EF__min_samples_leaf": [2, 4 ,8], 
                  "EF__min_samples_split": [2, 4 ,8],
                  "EF__n_estimators" : [20, 40, 80, 100, 120],
                  "EF__max_features" : [2 , 4, 6, 10, 15, 20, 25],
                  "EF__max_leaf_nodes" : [5, 10, 15, 20],
                  "selector__k": range(50, 150, 10)
                  }                                               
# pipeline.get_params().keys()
search = RandomizedSearchCV(
    estimator = pipeline,
    param_distributions = param_grid,
    n_iter = 10, 
    return_train_score = True,
    n_jobs= -1,
    scoring="f1",
    cv = 5,
    verbose=3)

search = search.fit(X_train, Y_train)
print(search.best_params_, search.best_score_)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
{'selector__k': 80, 'EF__n_estimators': 100, 'EF__min_samples_split': 8, 'EF__min_samples_leaf': 8, 'EF__max_samples': 0.2, 'EF__max_leaf_nodes': 10, 'EF__max_features': 2, 'EF__max_depth': 15} 0.6411369794751092


In [ ]:
MI_train = SelectKBest(mutual_info_classif, k = 80).fit_transform(X_train, Y_train),
MI_test = SelectKBest(mutual_info_classif, k = 80).fit_transform(X_test, Y_test)
RF(MI_train, Y_train, MI_test, Y_test, [100, 8, 8, 0.2, 10, 2, 15])

In [83]:
# RFE - Orginal model
estimator = RandomForestClassifier(n_jobs = -1, oob_score = True,random_state = 42, class_weight= "balanced", 
                                n_estimators = 100,
                                min_samples_split = 2,
                                min_samples_leaf = 2,
                                max_samples = 0.1,
                                max_leaf_nodes = 10,
                                max_depth = 4
                                )
selector = RFECV(estimator, step = 1, cv = KF, n_jobs = -1, scoring = "f1").fit(X_train, Y_train)
print(selector.n_features_, selector.ranking_)

86 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1 17  1 10  1
  1  1  1 46  1  1  1  1  1  1  1  1  1 28  7  1  1  1  1  1 31  1  1  1
  1  1  1  1 44 38 36 40 45  1 14  1 20  1 25  1 33 47 49 51  1 54  1 23
 61  1  1  1  9 71 70  3  1  1 26 11 24  1 12 29  5  1 32  1  1  1  1  1
 16  1  1  1  1  1  1  1  1  1 42 18  1  1  1  1  8 39 34 27 37  6 35 30
  1 22  1 50 41  4 15  1  1  1  1  1  1  1 13  1 19 21 43 48 52 53 55 56
 57 58 59 60 62 63 64 65 66 67 68 69]


In [84]:
RFE = pd.DataFrame(selector.support_, index = X_train.columns).rename(columns = {0:"selected"})  
RFE_train, RFE_test = X_train[RFE[RFE.selected == True].index], X_test[RFE[RFE.selected == True].index]
RF(RFE_train, Y_train, RFE_test, Y_test, [100, 2, 2, 0.1, 10, 4, 15])

(array([0.63617307, 0.63652923, 0.63464654]),
 0.6357536528673117,
 0.6456241952119516,
 array([[52505, 25349],
        [29968, 48275]]),
 array([0.62306433, 0.63440045, 0.63604143]),
 0.6350589757013951,
 0.6457346148671879,
 array([[22578, 11066],
        [12634, 20621]]),
 3.233290910720825)

In [81]:
# Select from moel - logsitic
Model_sel = SelectFromModel(estimator = estimator).fit(X_train, Y_train)
Model_selected = pd.DataFrame(Model_sel.get_support(), index = X_train.columns).rename(columns = {0: "selected"})
ms_train, ms_test = X_train[Model_selected[Model_selected.selected == True].index], X_test[Model_selected[Model_selected.selected == True].index]

In [82]:
RF(ms_train, Y_train, ms_test, Y_test, params = [100, 2, 2, 0.1, 10, 4, 15])

(array([0.62339345, 0.62502263, 0.62226167]),
 0.6264262939418854,
 0.6419726195891017,
 array([[53353, 24501],
        [31386, 46857]]),
 array([0.61037394, 0.62024457, 0.62592212]),
 0.6262951444779572,
 0.6425507107729562,
 array([[22948, 10696],
        [13217, 20038]]),
 1.9438858032226562)

### CatBoost

In [103]:
CATboost = CatBoostClassifier(random_seed = 42, boosting_type = "Plain", eval_metric = "F1", od_type = "IncToDec", 
                              bootstrap_type = "Bernoulli")
grid = {"iterations" :[100, 500, 1000, 2000],
        "learning_rate": [0.0003, 0.003, 0.03, 0.3],
        "l2_leaf_reg": [3, 9, 18, 25, 35],
        "depth" : [10, 12 , 14 ,16],
        "rsm": [0.3, 0.5, 0.7],
        "min_data_in_leaf": [2, 4, 8, 10], 
       }

randomized_search_result = CATboost.randomized_search(grid,
                                                       X= X_train,
                                                       y= Y_train,
                                                       cv = KF, 
                                                       n_iter = 10,
                                                       shuffle = True,
                                                       search_by_train_test_split = True,
                                                       plot=True)

Custom logger is already specified. Specify more than one logger at same time is not thread safe.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.6462352	test: 0.6378378	best: 0.6378378 (0)	total: 310ms	remaining: 2m 34s
1:	learn: 0.6752203	test: 0.6542461	best: 0.6542461 (1)	total: 638ms	remaining: 2m 38s
2:	learn: 0.6814327	test: 0.6588823	best: 0.6588823 (2)	total: 961ms	remaining: 2m 39s
3:	learn: 0.6895746	test: 0.6641482	best: 0.6641482 (3)	total: 1.32s	remaining: 2m 43s
4:	learn: 0.7031194	test: 0.6730592	best: 0.6730592 (4)	total: 1.65s	remaining: 2m 43s
5:	learn: 0.7163041	test: 0.6815082	best: 0.6815082 (5)	total: 1.98s	remaining: 2m 42s
6:	learn: 0.7248423	test: 0.6862996	best: 0.6862996 (6)	total: 2.3s	remaining: 2m 42s
7:	learn: 0.7277466	test: 0.6875555	best: 0.6875555 (7)	total: 2.61s	remaining: 2m 40s
8:	learn: 0.7323937	test: 0.6910681	best: 0.6910681 (8)	total: 2.94s	remaining: 2m 40s
9:	learn: 0.7400513	test: 0.6950833	best: 0.6950833 (9)	total: 3.28s	remaining: 2m 40s
10:	learn: 0.7471110	test: 0.7000989	best: 0.7000989 (10)	total: 3.61s	remaining: 2m 40s
11:	learn: 0.7504588	test: 0.7010445	best:

93:	learn: 0.9575883	test: 0.8206451	best: 0.8206451 (93)	total: 28.8s	remaining: 2m 4s
94:	learn: 0.9588579	test: 0.8212489	best: 0.8212489 (94)	total: 29.1s	remaining: 2m 4s
95:	learn: 0.9596698	test: 0.8219785	best: 0.8219785 (95)	total: 29.4s	remaining: 2m 3s
96:	learn: 0.9603186	test: 0.8235176	best: 0.8235176 (96)	total: 29.7s	remaining: 2m 3s
97:	learn: 0.9611174	test: 0.8237345	best: 0.8237345 (97)	total: 30s	remaining: 2m 3s
98:	learn: 0.9622740	test: 0.8242083	best: 0.8242083 (98)	total: 30.3s	remaining: 2m 2s
99:	learn: 0.9626182	test: 0.8245002	best: 0.8245002 (99)	total: 30.6s	remaining: 2m 2s
100:	learn: 0.9638572	test: 0.8257939	best: 0.8257939 (100)	total: 30.9s	remaining: 2m 2s
101:	learn: 0.9654796	test: 0.8271766	best: 0.8271766 (101)	total: 31.3s	remaining: 2m 1s
102:	learn: 0.9667308	test: 0.8277298	best: 0.8277298 (102)	total: 31.6s	remaining: 2m 1s
103:	learn: 0.9682992	test: 0.8284409	best: 0.8284409 (103)	total: 31.9s	remaining: 2m 1s
104:	learn: 0.9696465	test

184:	learn: 0.9974997	test: 0.8693721	best: 0.8693721 (184)	total: 56.9s	remaining: 1m 36s
185:	learn: 0.9976354	test: 0.8702321	best: 0.8702321 (185)	total: 57.2s	remaining: 1m 36s
186:	learn: 0.9976513	test: 0.8702557	best: 0.8702557 (186)	total: 57.5s	remaining: 1m 36s
187:	learn: 0.9977072	test: 0.8712432	best: 0.8712432 (187)	total: 57.8s	remaining: 1m 35s
188:	learn: 0.9977391	test: 0.8713930	best: 0.8713930 (188)	total: 58.1s	remaining: 1m 35s
189:	learn: 0.9978509	test: 0.8717345	best: 0.8717345 (189)	total: 58.4s	remaining: 1m 35s
190:	learn: 0.9979226	test: 0.8716587	best: 0.8717345 (189)	total: 58.7s	remaining: 1m 35s
191:	learn: 0.9979146	test: 0.8712119	best: 0.8717345 (189)	total: 59s	remaining: 1m 34s
192:	learn: 0.9978986	test: 0.8716759	best: 0.8717345 (189)	total: 59.3s	remaining: 1m 34s
193:	learn: 0.9979546	test: 0.8713431	best: 0.8717345 (189)	total: 59.6s	remaining: 1m 34s
194:	learn: 0.9980185	test: 0.8718725	best: 0.8718725 (194)	total: 59.9s	remaining: 1m 33s
1

274:	learn: 0.9999600	test: 0.8837941	best: 0.8837941 (274)	total: 1m 25s	remaining: 1m 9s
275:	learn: 0.9999680	test: 0.8837552	best: 0.8837941 (274)	total: 1m 25s	remaining: 1m 9s
276:	learn: 0.9999680	test: 0.8836089	best: 0.8837941 (274)	total: 1m 26s	remaining: 1m 9s
277:	learn: 0.9999760	test: 0.8839746	best: 0.8839746 (277)	total: 1m 26s	remaining: 1m 8s
278:	learn: 0.9999760	test: 0.8835793	best: 0.8839746 (277)	total: 1m 26s	remaining: 1m 8s
279:	learn: 0.9999760	test: 0.8839450	best: 0.8839746 (277)	total: 1m 26s	remaining: 1m 8s
280:	learn: 0.9999680	test: 0.8840056	best: 0.8840056 (280)	total: 1m 27s	remaining: 1m 8s
281:	learn: 0.9999680	test: 0.8844211	best: 0.8844211 (281)	total: 1m 27s	remaining: 1m 7s
282:	learn: 0.9999680	test: 0.8844893	best: 0.8844893 (282)	total: 1m 27s	remaining: 1m 7s
283:	learn: 0.9999680	test: 0.8840041	best: 0.8844893 (282)	total: 1m 28s	remaining: 1m 7s
284:	learn: 0.9999760	test: 0.8841598	best: 0.8844893 (282)	total: 1m 28s	remaining: 1m 6s

365:	learn: 1.0000000	test: 0.8903350	best: 0.8903350 (365)	total: 1m 53s	remaining: 41.5s
366:	learn: 1.0000000	test: 0.8900475	best: 0.8903350 (365)	total: 1m 53s	remaining: 41.2s
367:	learn: 1.0000000	test: 0.8902099	best: 0.8903350 (365)	total: 1m 53s	remaining: 40.9s
368:	learn: 1.0000000	test: 0.8899372	best: 0.8903350 (365)	total: 1m 54s	remaining: 40.6s
369:	learn: 1.0000000	test: 0.8901508	best: 0.8903350 (365)	total: 1m 54s	remaining: 40.3s
370:	learn: 1.0000000	test: 0.8905265	best: 0.8905265 (370)	total: 1m 54s	remaining: 39.9s
371:	learn: 1.0000000	test: 0.8905265	best: 0.8905265 (370)	total: 1m 55s	remaining: 39.6s
372:	learn: 1.0000000	test: 0.8905560	best: 0.8905560 (372)	total: 1m 55s	remaining: 39.3s
373:	learn: 1.0000000	test: 0.8907987	best: 0.8907987 (373)	total: 1m 55s	remaining: 39s
374:	learn: 1.0000000	test: 0.8905410	best: 0.8907987 (373)	total: 1m 56s	remaining: 38.7s
375:	learn: 1.0000000	test: 0.8904010	best: 0.8907987 (373)	total: 1m 56s	remaining: 38.4s
3

456:	learn: 1.0000000	test: 0.8935691	best: 0.8937748 (453)	total: 2m 21s	remaining: 13.3s
457:	learn: 1.0000000	test: 0.8937001	best: 0.8937748 (453)	total: 2m 21s	remaining: 13s
458:	learn: 1.0000000	test: 0.8931872	best: 0.8937748 (453)	total: 2m 21s	remaining: 12.7s
459:	learn: 1.0000000	test: 0.8933563	best: 0.8937748 (453)	total: 2m 22s	remaining: 12.4s
460:	learn: 1.0000000	test: 0.8931068	best: 0.8937748 (453)	total: 2m 22s	remaining: 12.1s
461:	learn: 1.0000000	test: 0.8932675	best: 0.8937748 (453)	total: 2m 22s	remaining: 11.7s
462:	learn: 1.0000000	test: 0.8931055	best: 0.8937748 (453)	total: 2m 23s	remaining: 11.4s
463:	learn: 1.0000000	test: 0.8933170	best: 0.8937748 (453)	total: 2m 23s	remaining: 11.1s
464:	learn: 1.0000000	test: 0.8933466	best: 0.8937748 (453)	total: 2m 23s	remaining: 10.8s
465:	learn: 1.0000000	test: 0.8934282	best: 0.8937748 (453)	total: 2m 24s	remaining: 10.5s
466:	learn: 1.0000000	test: 0.8934790	best: 0.8937748 (453)	total: 2m 24s	remaining: 10.2s
4

46:	learn: 0.6928290	test: 0.6634557	best: 0.6637914 (45)	total: 51.3s	remaining: 35m 31s
47:	learn: 0.6925568	test: 0.6636133	best: 0.6637914 (45)	total: 52.4s	remaining: 35m 30s
48:	learn: 0.6930475	test: 0.6641484	best: 0.6641484 (48)	total: 53.5s	remaining: 35m 30s
49:	learn: 0.6944987	test: 0.6643478	best: 0.6643478 (49)	total: 54.6s	remaining: 35m 29s
50:	learn: 0.6943472	test: 0.6645936	best: 0.6645936 (50)	total: 55.7s	remaining: 35m 28s
51:	learn: 0.6944419	test: 0.6644143	best: 0.6645936 (50)	total: 56.8s	remaining: 35m 29s
52:	learn: 0.6938465	test: 0.6643235	best: 0.6645936 (50)	total: 57.9s	remaining: 35m 28s
53:	learn: 0.6932640	test: 0.6641911	best: 0.6645936 (50)	total: 59s	remaining: 35m 27s
54:	learn: 0.6928117	test: 0.6640345	best: 0.6645936 (50)	total: 1m	remaining: 35m 24s
55:	learn: 0.6934167	test: 0.6641681	best: 0.6645936 (50)	total: 1m 1s	remaining: 35m 23s
56:	learn: 0.6933541	test: 0.6642363	best: 0.6645936 (50)	total: 1m 2s	remaining: 35m 22s
57:	learn: 0.69

137:	learn: 0.7000585	test: 0.6661312	best: 0.6663101 (132)	total: 2m 30s	remaining: 33m 57s
138:	learn: 0.7001445	test: 0.6660869	best: 0.6663101 (132)	total: 2m 32s	remaining: 33m 57s
139:	learn: 0.7001913	test: 0.6663545	best: 0.6663545 (139)	total: 2m 33s	remaining: 33m 57s
140:	learn: 0.7001604	test: 0.6663101	best: 0.6663545 (139)	total: 2m 34s	remaining: 33m 57s
141:	learn: 0.7003425	test: 0.6664883	best: 0.6664883 (141)	total: 2m 35s	remaining: 33m 57s
142:	learn: 0.7001462	test: 0.6664214	best: 0.6664883 (141)	total: 2m 36s	remaining: 33m 57s
143:	learn: 0.7002281	test: 0.6663991	best: 0.6664883 (141)	total: 2m 38s	remaining: 33m 57s
144:	learn: 0.7002047	test: 0.6663991	best: 0.6664883 (141)	total: 2m 39s	remaining: 33m 58s
145:	learn: 0.7004411	test: 0.6667336	best: 0.6667336 (145)	total: 2m 40s	remaining: 33m 58s
146:	learn: 0.7006224	test: 0.6665998	best: 0.6667336 (145)	total: 2m 41s	remaining: 33m 59s
147:	learn: 0.7004252	test: 0.6664437	best: 0.6667336 (145)	total: 2m 

226:	learn: 0.7070680	test: 0.6715011	best: 0.6718118 (224)	total: 4m 10s	remaining: 32m 39s
227:	learn: 0.7070003	test: 0.6718338	best: 0.6718338 (227)	total: 4m 11s	remaining: 32m 37s
228:	learn: 0.7071278	test: 0.6721454	best: 0.6721454 (228)	total: 4m 12s	remaining: 32m 36s
229:	learn: 0.7071240	test: 0.6720347	best: 0.6721454 (228)	total: 4m 13s	remaining: 32m 34s
230:	learn: 0.7071830	test: 0.6722582	best: 0.6722582 (230)	total: 4m 15s	remaining: 32m 33s
231:	learn: 0.7074050	test: 0.6721476	best: 0.6722582 (230)	total: 4m 16s	remaining: 32m 31s
232:	learn: 0.7073030	test: 0.6720813	best: 0.6722582 (230)	total: 4m 17s	remaining: 32m 30s
233:	learn: 0.7075621	test: 0.6719936	best: 0.6722582 (230)	total: 4m 18s	remaining: 32m 29s
234:	learn: 0.7076867	test: 0.6719701	best: 0.6722582 (230)	total: 4m 19s	remaining: 32m 27s
235:	learn: 0.7077945	test: 0.6721931	best: 0.6722582 (230)	total: 4m 20s	remaining: 32m 26s
236:	learn: 0.7076107	test: 0.6717465	best: 0.6722582 (230)	total: 4m 

315:	learn: 0.7149218	test: 0.6760074	best: 0.6763408 (313)	total: 5m 47s	remaining: 30m 50s
316:	learn: 0.7149383	test: 0.6761844	best: 0.6763408 (313)	total: 5m 48s	remaining: 30m 49s
317:	learn: 0.7148158	test: 0.6760516	best: 0.6763408 (313)	total: 5m 49s	remaining: 30m 47s
318:	learn: 0.7150005	test: 0.6762739	best: 0.6763408 (313)	total: 5m 50s	remaining: 30m 47s
319:	learn: 0.7152006	test: 0.6762089	best: 0.6763408 (313)	total: 5m 51s	remaining: 30m 46s
320:	learn: 0.7152577	test: 0.6761185	best: 0.6763408 (313)	total: 5m 52s	remaining: 30m 45s
321:	learn: 0.7153017	test: 0.6761844	best: 0.6763408 (313)	total: 5m 53s	remaining: 30m 43s
322:	learn: 0.7154042	test: 0.6764971	best: 0.6764971 (322)	total: 5m 54s	remaining: 30m 42s
323:	learn: 0.7156210	test: 0.6767194	best: 0.6767194 (323)	total: 5m 55s	remaining: 30m 41s
324:	learn: 0.7157577	test: 0.6765817	best: 0.6767194 (323)	total: 5m 57s	remaining: 30m 40s
325:	learn: 0.7157317	test: 0.6767626	best: 0.6767626 (325)	total: 5m 

404:	learn: 0.7230523	test: 0.6810601	best: 0.6811270 (403)	total: 7m 26s	remaining: 29m 19s
405:	learn: 0.7231179	test: 0.6812548	best: 0.6812548 (405)	total: 7m 27s	remaining: 29m 18s
406:	learn: 0.7231533	test: 0.6812335	best: 0.6812548 (405)	total: 7m 29s	remaining: 29m 17s
407:	learn: 0.7233465	test: 0.6813429	best: 0.6813429 (407)	total: 7m 30s	remaining: 29m 16s
408:	learn: 0.7234131	test: 0.6812137	best: 0.6813429 (407)	total: 7m 31s	remaining: 29m 15s
409:	learn: 0.7235318	test: 0.6812849	best: 0.6813429 (407)	total: 7m 32s	remaining: 29m 13s
410:	learn: 0.7235003	test: 0.6812563	best: 0.6813429 (407)	total: 7m 33s	remaining: 29m 12s
411:	learn: 0.7235007	test: 0.6814399	best: 0.6814399 (411)	total: 7m 34s	remaining: 29m 11s
412:	learn: 0.7234967	test: 0.6814825	best: 0.6814825 (412)	total: 7m 35s	remaining: 29m 10s
413:	learn: 0.7235244	test: 0.6812790	best: 0.6814825 (412)	total: 7m 36s	remaining: 29m 9s
414:	learn: 0.7236434	test: 0.6815236	best: 0.6815236 (414)	total: 7m 3

493:	learn: 0.7294934	test: 0.6861226	best: 0.6864296 (488)	total: 9m 2s	remaining: 27m 33s
494:	learn: 0.7295073	test: 0.6864506	best: 0.6864506 (494)	total: 9m 3s	remaining: 27m 32s
495:	learn: 0.7296544	test: 0.6864296	best: 0.6864506 (494)	total: 9m 4s	remaining: 27m 31s
496:	learn: 0.7295739	test: 0.6863838	best: 0.6864506 (494)	total: 9m 5s	remaining: 27m 30s
497:	learn: 0.7297554	test: 0.6863629	best: 0.6864506 (494)	total: 9m 6s	remaining: 27m 29s
498:	learn: 0.7299236	test: 0.6863668	best: 0.6864506 (494)	total: 9m 7s	remaining: 27m 27s
499:	learn: 0.7300007	test: 0.6863917	best: 0.6864506 (494)	total: 9m 8s	remaining: 27m 26s
500:	learn: 0.7301254	test: 0.6864186	best: 0.6864506 (494)	total: 9m 10s	remaining: 27m 25s
501:	learn: 0.7301933	test: 0.6865522	best: 0.6865522 (501)	total: 9m 11s	remaining: 27m 24s
502:	learn: 0.7302237	test: 0.6865502	best: 0.6865522 (501)	total: 9m 12s	remaining: 27m 23s
503:	learn: 0.7302523	test: 0.6865063	best: 0.6865522 (501)	total: 9m 13s	rem

582:	learn: 0.7370231	test: 0.6897909	best: 0.6898553 (580)	total: 10m 39s	remaining: 25m 53s
583:	learn: 0.7371219	test: 0.6900323	best: 0.6900323 (583)	total: 10m 40s	remaining: 25m 51s
584:	learn: 0.7371823	test: 0.6897932	best: 0.6900323 (583)	total: 10m 41s	remaining: 25m 50s
585:	learn: 0.7372024	test: 0.6898392	best: 0.6900323 (583)	total: 10m 42s	remaining: 25m 49s
586:	learn: 0.7371508	test: 0.6899013	best: 0.6900323 (583)	total: 10m 43s	remaining: 25m 48s
587:	learn: 0.7372759	test: 0.6903039	best: 0.6903039 (587)	total: 10m 44s	remaining: 25m 47s
588:	learn: 0.7373905	test: 0.6900187	best: 0.6903039 (587)	total: 10m 45s	remaining: 25m 46s
589:	learn: 0.7375706	test: 0.6901498	best: 0.6903039 (587)	total: 10m 46s	remaining: 25m 45s
590:	learn: 0.7376519	test: 0.6900854	best: 0.6903039 (587)	total: 10m 47s	remaining: 25m 44s
591:	learn: 0.7376642	test: 0.6900163	best: 0.6903039 (587)	total: 10m 48s	remaining: 25m 42s
592:	learn: 0.7376774	test: 0.6904627	best: 0.6904627 (592)	

670:	learn: 0.7442602	test: 0.6945130	best: 0.6946028 (669)	total: 12m 21s	remaining: 24m 29s
671:	learn: 0.7443995	test: 0.6948028	best: 0.6948028 (671)	total: 12m 23s	remaining: 24m 28s
672:	learn: 0.7443806	test: 0.6948463	best: 0.6948463 (672)	total: 12m 24s	remaining: 24m 27s
673:	learn: 0.7444188	test: 0.6948435	best: 0.6948463 (672)	total: 12m 25s	remaining: 24m 26s
674:	learn: 0.7443856	test: 0.6949480	best: 0.6949480 (674)	total: 12m 26s	remaining: 24m 25s
675:	learn: 0.7446014	test: 0.6949537	best: 0.6949537 (675)	total: 12m 27s	remaining: 24m 24s
676:	learn: 0.7445936	test: 0.6950638	best: 0.6950638 (676)	total: 12m 29s	remaining: 24m 24s
677:	learn: 0.7445878	test: 0.6947972	best: 0.6950638 (676)	total: 12m 30s	remaining: 24m 22s
678:	learn: 0.7446523	test: 0.6947972	best: 0.6950638 (676)	total: 12m 31s	remaining: 24m 21s
679:	learn: 0.7446839	test: 0.6949480	best: 0.6950638 (676)	total: 12m 32s	remaining: 24m 20s
680:	learn: 0.7448117	test: 0.6949593	best: 0.6950638 (676)	

758:	learn: 0.7505988	test: 0.6992108	best: 0.6993007 (754)	total: 14m 2s	remaining: 22m 58s
759:	learn: 0.7507769	test: 0.6990143	best: 0.6993007 (754)	total: 14m 3s	remaining: 22m 57s
760:	learn: 0.7508682	test: 0.6992141	best: 0.6993007 (754)	total: 14m 5s	remaining: 22m 55s
761:	learn: 0.7510008	test: 0.6992606	best: 0.6993007 (754)	total: 14m 6s	remaining: 22m 54s
762:	learn: 0.7509904	test: 0.6993473	best: 0.6993473 (762)	total: 14m 7s	remaining: 22m 53s
763:	learn: 0.7509407	test: 0.6993040	best: 0.6993473 (762)	total: 14m 8s	remaining: 22m 52s
764:	learn: 0.7510153	test: 0.6996104	best: 0.6996104 (764)	total: 14m 9s	remaining: 22m 51s
765:	learn: 0.7510421	test: 0.6995871	best: 0.6996104 (764)	total: 14m 10s	remaining: 22m 50s
766:	learn: 0.7510814	test: 0.6995704	best: 0.6996104 (764)	total: 14m 11s	remaining: 22m 49s
767:	learn: 0.7511497	test: 0.6997636	best: 0.6997636 (767)	total: 14m 13s	remaining: 22m 48s
768:	learn: 0.7513508	test: 0.6997469	best: 0.6997636 (767)	total: 

846:	learn: 0.7571067	test: 0.7030392	best: 0.7031328 (842)	total: 15m 40s	remaining: 21m 20s
847:	learn: 0.7572893	test: 0.7032228	best: 0.7032228 (847)	total: 15m 41s	remaining: 21m 19s
848:	learn: 0.7572311	test: 0.7032228	best: 0.7032228 (847)	total: 15m 42s	remaining: 21m 17s
849:	learn: 0.7573053	test: 0.7031599	best: 0.7032228 (847)	total: 15m 43s	remaining: 21m 16s
850:	learn: 0.7573515	test: 0.7030501	best: 0.7032228 (847)	total: 15m 44s	remaining: 21m 15s
851:	learn: 0.7573886	test: 0.7026235	best: 0.7032228 (847)	total: 15m 46s	remaining: 21m 14s
852:	learn: 0.7575672	test: 0.7032660	best: 0.7032660 (852)	total: 15m 47s	remaining: 21m 13s
853:	learn: 0.7575605	test: 0.7033362	best: 0.7033362 (853)	total: 15m 48s	remaining: 21m 12s
854:	learn: 0.7576616	test: 0.7032660	best: 0.7033362 (853)	total: 15m 49s	remaining: 21m 11s
855:	learn: 0.7577335	test: 0.7032894	best: 0.7033362 (853)	total: 15m 50s	remaining: 21m 10s
856:	learn: 0.7578397	test: 0.7033596	best: 0.7033596 (856)	

934:	learn: 0.7631731	test: 0.7072709	best: 0.7072984 (933)	total: 17m 20s	remaining: 19m 45s
935:	learn: 0.7633283	test: 0.7074192	best: 0.7074192 (935)	total: 17m 21s	remaining: 19m 43s
936:	learn: 0.7633756	test: 0.7072279	best: 0.7074192 (935)	total: 17m 22s	remaining: 19m 42s
937:	learn: 0.7633229	test: 0.7072084	best: 0.7074192 (935)	total: 17m 23s	remaining: 19m 41s
938:	learn: 0.7634339	test: 0.7072749	best: 0.7074192 (935)	total: 17m 24s	remaining: 19m 40s
939:	learn: 0.7635527	test: 0.7074898	best: 0.7074898 (939)	total: 17m 26s	remaining: 19m 39s
940:	learn: 0.7635804	test: 0.7076350	best: 0.7076350 (940)	total: 17m 27s	remaining: 19m 38s
941:	learn: 0.7636379	test: 0.7077639	best: 0.7077639 (941)	total: 17m 28s	remaining: 19m 37s
942:	learn: 0.7636409	test: 0.7077322	best: 0.7077639 (941)	total: 17m 29s	remaining: 19m 36s
943:	learn: 0.7636691	test: 0.7077322	best: 0.7077639 (941)	total: 17m 30s	remaining: 19m 35s
944:	learn: 0.7637630	test: 0.7077946	best: 0.7077946 (944)	

1021:	learn: 0.7688811	test: 0.7101810	best: 0.7102090 (1020)	total: 18m 58s	remaining: 18m 9s
1022:	learn: 0.7690846	test: 0.7101382	best: 0.7102090 (1020)	total: 18m 59s	remaining: 18m 7s
1023:	learn: 0.7691532	test: 0.7102475	best: 0.7102475 (1023)	total: 19m	remaining: 18m 6s
1024:	learn: 0.7691583	test: 0.7102860	best: 0.7102860 (1024)	total: 19m 1s	remaining: 18m 5s
1025:	learn: 0.7692600	test: 0.7103567	best: 0.7103567 (1025)	total: 19m 2s	remaining: 18m 4s
1026:	learn: 0.7693922	test: 0.7102046	best: 0.7103567 (1025)	total: 19m 3s	remaining: 18m 3s
1027:	learn: 0.7694558	test: 0.7102667	best: 0.7103567 (1025)	total: 19m 4s	remaining: 18m 2s
1028:	learn: 0.7695842	test: 0.7102518	best: 0.7103567 (1025)	total: 19m 5s	remaining: 18m 1s
1029:	learn: 0.7697000	test: 0.7105176	best: 0.7105176 (1029)	total: 19m 7s	remaining: 18m
1030:	learn: 0.7696872	test: 0.7105324	best: 0.7105324 (1030)	total: 19m 8s	remaining: 17m 59s
1031:	learn: 0.7697686	test: 0.7107273	best: 0.7107273 (1031)	t

1107:	learn: 0.7746196	test: 0.7134600	best: 0.7134600 (1107)	total: 20m 36s	remaining: 16m 35s
1108:	learn: 0.7747230	test: 0.7137067	best: 0.7137067 (1108)	total: 20m 38s	remaining: 16m 34s
1109:	learn: 0.7748103	test: 0.7137685	best: 0.7137685 (1109)	total: 20m 39s	remaining: 16m 33s
1110:	learn: 0.7749418	test: 0.7137258	best: 0.7137685 (1109)	total: 20m 40s	remaining: 16m 32s
1111:	learn: 0.7749189	test: 0.7137258	best: 0.7137685 (1109)	total: 20m 41s	remaining: 16m 31s
1112:	learn: 0.7750105	test: 0.7138586	best: 0.7138586 (1112)	total: 20m 43s	remaining: 16m 30s
1113:	learn: 0.7751548	test: 0.7138112	best: 0.7138586 (1112)	total: 20m 44s	remaining: 16m 29s
1114:	learn: 0.7751521	test: 0.7139394	best: 0.7139394 (1114)	total: 20m 45s	remaining: 16m 28s
1115:	learn: 0.7752666	test: 0.7140579	best: 0.7140579 (1115)	total: 20m 46s	remaining: 16m 27s
1116:	learn: 0.7752969	test: 0.7140769	best: 0.7140769 (1116)	total: 20m 47s	remaining: 16m 26s
1117:	learn: 0.7753060	test: 0.7142572	b

1193:	learn: 0.7800776	test: 0.7174837	best: 0.7174837 (1193)	total: 22m 12s	remaining: 14m 59s
1194:	learn: 0.7800611	test: 0.7175689	best: 0.7175689 (1194)	total: 22m 13s	remaining: 14m 58s
1195:	learn: 0.7801150	test: 0.7176541	best: 0.7176541 (1195)	total: 22m 14s	remaining: 14m 57s
1196:	learn: 0.7802024	test: 0.7178057	best: 0.7178057 (1196)	total: 22m 15s	remaining: 14m 56s
1197:	learn: 0.7802249	test: 0.7177393	best: 0.7178057 (1196)	total: 22m 16s	remaining: 14m 54s
1198:	learn: 0.7801928	test: 0.7177154	best: 0.7178057 (1196)	total: 22m 17s	remaining: 14m 53s
1199:	learn: 0.7804592	test: 0.7176592	best: 0.7178057 (1196)	total: 22m 19s	remaining: 14m 52s
1200:	learn: 0.7804041	test: 0.7174974	best: 0.7178057 (1196)	total: 22m 20s	remaining: 14m 51s
1201:	learn: 0.7804464	test: 0.7176252	best: 0.7178057 (1196)	total: 22m 21s	remaining: 14m 50s
1202:	learn: 0.7805168	test: 0.7174599	best: 0.7178057 (1196)	total: 22m 22s	remaining: 14m 49s
1203:	learn: 0.7806931	test: 0.7175978	b

1279:	learn: 0.7857202	test: 0.7212527	best: 0.7213670 (1274)	total: 23m 46s	remaining: 13m 22s
1280:	learn: 0.7856901	test: 0.7211494	best: 0.7213670 (1274)	total: 23m 47s	remaining: 13m 21s
1281:	learn: 0.7858491	test: 0.7212636	best: 0.7213670 (1274)	total: 23m 49s	remaining: 13m 20s
1282:	learn: 0.7858261	test: 0.7211255	best: 0.7213670 (1274)	total: 23m 50s	remaining: 13m 19s
1283:	learn: 0.7858208	test: 0.7209927	best: 0.7213670 (1274)	total: 23m 51s	remaining: 13m 18s
1284:	learn: 0.7859392	test: 0.7211069	best: 0.7213670 (1274)	total: 23m 52s	remaining: 13m 17s
1285:	learn: 0.7860587	test: 0.7211972	best: 0.7213670 (1274)	total: 23m 53s	remaining: 13m 15s
1286:	learn: 0.7861717	test: 0.7212821	best: 0.7213670 (1274)	total: 23m 54s	remaining: 13m 14s
1287:	learn: 0.7862135	test: 0.7214942	best: 0.7214942 (1287)	total: 23m 55s	remaining: 13m 13s
1288:	learn: 0.7862965	test: 0.7215845	best: 0.7215845 (1288)	total: 23m 56s	remaining: 13m 12s
1289:	learn: 0.7863394	test: 0.7215660	b

1365:	learn: 0.7905034	test: 0.7244993	best: 0.7244993 (1365)	total: 25m 21s	remaining: 11m 46s
1366:	learn: 0.7906586	test: 0.7245348	best: 0.7245348 (1366)	total: 25m 22s	remaining: 11m 45s
1367:	learn: 0.7907276	test: 0.7245531	best: 0.7245531 (1367)	total: 25m 23s	remaining: 11m 43s
1368:	learn: 0.7907214	test: 0.7245108	best: 0.7245531 (1367)	total: 25m 24s	remaining: 11m 42s
1369:	learn: 0.7907605	test: 0.7245165	best: 0.7245531 (1367)	total: 25m 25s	remaining: 11m 41s
1370:	learn: 0.7909191	test: 0.7245646	best: 0.7245646 (1370)	total: 25m 26s	remaining: 11m 40s
1371:	learn: 0.7909593	test: 0.7245829	best: 0.7245829 (1371)	total: 25m 28s	remaining: 11m 39s
1372:	learn: 0.7910015	test: 0.7245829	best: 0.7245829 (1371)	total: 25m 29s	remaining: 11m 38s
1373:	learn: 0.7911371	test: 0.7248847	best: 0.7248847 (1373)	total: 25m 30s	remaining: 11m 37s
1374:	learn: 0.7911739	test: 0.7248905	best: 0.7248905 (1374)	total: 25m 31s	remaining: 11m 36s
1375:	learn: 0.7912405	test: 0.7247819	b

1451:	learn: 0.7955212	test: 0.7271099	best: 0.7271461 (1447)	total: 26m 57s	remaining: 10m 10s
1452:	learn: 0.7955936	test: 0.7272185	best: 0.7272185 (1452)	total: 26m 58s	remaining: 10m 9s
1453:	learn: 0.7956134	test: 0.7271763	best: 0.7272185 (1452)	total: 26m 59s	remaining: 10m 8s
1454:	learn: 0.7956267	test: 0.7272607	best: 0.7272607 (1454)	total: 27m	remaining: 10m 6s
1455:	learn: 0.7957846	test: 0.7273571	best: 0.7273571 (1455)	total: 27m 1s	remaining: 10m 5s
1456:	learn: 0.7958176	test: 0.7272968	best: 0.7273571 (1455)	total: 27m 2s	remaining: 10m 4s
1457:	learn: 0.7959562	test: 0.7272124	best: 0.7273571 (1455)	total: 27m 3s	remaining: 10m 3s
1458:	learn: 0.7959530	test: 0.7271702	best: 0.7273571 (1455)	total: 27m 4s	remaining: 10m 2s
1459:	learn: 0.7960156	test: 0.7272788	best: 0.7273571 (1455)	total: 27m 5s	remaining: 10m 1s
1460:	learn: 0.7960420	test: 0.7271943	best: 0.7273571 (1455)	total: 27m 7s	remaining: 10m
1461:	learn: 0.7960484	test: 0.7271280	best: 0.7273571 (1455)	

1538:	learn: 0.7999605	test: 0.7294680	best: 0.7296966 (1526)	total: 28m 33s	remaining: 8m 33s
1539:	learn: 0.8000230	test: 0.7297091	best: 0.7297091 (1539)	total: 28m 34s	remaining: 8m 32s
1540:	learn: 0.8002995	test: 0.7297333	best: 0.7297333 (1540)	total: 28m 35s	remaining: 8m 30s
1541:	learn: 0.8003193	test: 0.7297575	best: 0.7297575 (1541)	total: 28m 36s	remaining: 8m 29s
1542:	learn: 0.8004081	test: 0.7299502	best: 0.7299502 (1542)	total: 28m 37s	remaining: 8m 28s
1543:	learn: 0.8004345	test: 0.7299745	best: 0.7299745 (1543)	total: 28m 38s	remaining: 8m 27s
1544:	learn: 0.8004542	test: 0.7299987	best: 0.7299987 (1544)	total: 28m 39s	remaining: 8m 26s
1545:	learn: 0.8005003	test: 0.7300229	best: 0.7300229 (1545)	total: 28m 40s	remaining: 8m 25s
1546:	learn: 0.8004871	test: 0.7301071	best: 0.7301071 (1546)	total: 28m 41s	remaining: 8m 24s
1547:	learn: 0.8005727	test: 0.7301314	best: 0.7301314 (1547)	total: 28m 43s	remaining: 8m 23s
1548:	learn: 0.8005332	test: 0.7300713	best: 0.730

1625:	learn: 0.8048193	test: 0.7329996	best: 0.7330416 (1624)	total: 30m 7s	remaining: 6m 55s
1626:	learn: 0.8049111	test: 0.7329576	best: 0.7330416 (1624)	total: 30m 8s	remaining: 6m 54s
1627:	learn: 0.8049671	test: 0.7330659	best: 0.7330659 (1627)	total: 30m 10s	remaining: 6m 53s
1628:	learn: 0.8050425	test: 0.7330416	best: 0.7330659 (1627)	total: 30m 11s	remaining: 6m 52s
1629:	learn: 0.8050558	test: 0.7330305	best: 0.7330659 (1627)	total: 30m 12s	remaining: 6m 51s
1630:	learn: 0.8051446	test: 0.7329708	best: 0.7330659 (1627)	total: 30m 13s	remaining: 6m 50s
1631:	learn: 0.8051608	test: 0.7331565	best: 0.7331565 (1631)	total: 30m 14s	remaining: 6m 49s
1632:	learn: 0.8052232	test: 0.7329819	best: 0.7331565 (1631)	total: 30m 16s	remaining: 6m 48s
1633:	learn: 0.8052732	test: 0.7329642	best: 0.7331565 (1631)	total: 30m 17s	remaining: 6m 47s
1634:	learn: 0.8054082	test: 0.7331874	best: 0.7331874 (1634)	total: 30m 18s	remaining: 6m 45s
1635:	learn: 0.8055560	test: 0.7332051	best: 0.73320

1712:	learn: 0.8089302	test: 0.7351039	best: 0.7352610 (1711)	total: 31m 44s	remaining: 5m 19s
1713:	learn: 0.8089138	test: 0.7350201	best: 0.7352610 (1711)	total: 31m 46s	remaining: 5m 18s
1714:	learn: 0.8089901	test: 0.7350688	best: 0.7352610 (1711)	total: 31m 47s	remaining: 5m 16s
1715:	learn: 0.8090726	test: 0.7352434	best: 0.7352610 (1711)	total: 31m 48s	remaining: 5m 15s
1716:	learn: 0.8091387	test: 0.7351771	best: 0.7352610 (1711)	total: 31m 49s	remaining: 5m 14s
1717:	learn: 0.8092115	test: 0.7351215	best: 0.7352610 (1711)	total: 31m 50s	remaining: 5m 13s
1718:	learn: 0.8092839	test: 0.7349537	best: 0.7352610 (1711)	total: 31m 51s	remaining: 5m 12s
1719:	learn: 0.8092334	test: 0.7351391	best: 0.7352610 (1711)	total: 31m 52s	remaining: 5m 11s
1720:	learn: 0.8093223	test: 0.7351703	best: 0.7352610 (1711)	total: 31m 53s	remaining: 5m 10s
1721:	learn: 0.8094334	test: 0.7352717	best: 0.7352717 (1721)	total: 31m 55s	remaining: 5m 9s
1722:	learn: 0.8094037	test: 0.7352054	best: 0.7352

1799:	learn: 0.8132327	test: 0.7373828	best: 0.7374002 (1794)	total: 33m 21s	remaining: 3m 42s
1800:	learn: 0.8133549	test: 0.7373409	best: 0.7374002 (1794)	total: 33m 22s	remaining: 3m 41s
1801:	learn: 0.8132728	test: 0.7372188	best: 0.7374002 (1794)	total: 33m 23s	remaining: 3m 40s
1802:	learn: 0.8133647	test: 0.7372676	best: 0.7374002 (1794)	total: 33m 24s	remaining: 3m 39s
1803:	learn: 0.8132928	test: 0.7372258	best: 0.7374002 (1794)	total: 33m 25s	remaining: 3m 37s
1804:	learn: 0.8133338	test: 0.7372258	best: 0.7374002 (1794)	total: 33m 26s	remaining: 3m 36s
1805:	learn: 0.8133928	test: 0.7372676	best: 0.7374002 (1794)	total: 33m 27s	remaining: 3m 35s
1806:	learn: 0.8134026	test: 0.7373757	best: 0.7374002 (1794)	total: 33m 28s	remaining: 3m 34s
1807:	learn: 0.8133820	test: 0.7374176	best: 0.7374176 (1807)	total: 33m 29s	remaining: 3m 33s
1808:	learn: 0.8136142	test: 0.7375746	best: 0.7375746 (1808)	total: 33m 31s	remaining: 3m 32s
1809:	learn: 0.8136301	test: 0.7374491	best: 0.737

1886:	learn: 0.8176828	test: 0.7401074	best: 0.7401147 (1884)	total: 34m 57s	remaining: 2m 5s
1887:	learn: 0.8176642	test: 0.7402081	best: 0.7402081 (1887)	total: 34m 58s	remaining: 2m 4s
1888:	learn: 0.8177150	test: 0.7401246	best: 0.7402081 (1887)	total: 34m 59s	remaining: 2m 3s
1889:	learn: 0.8178390	test: 0.7398913	best: 0.7402081 (1887)	total: 35m	remaining: 2m 2s
1890:	learn: 0.8178128	test: 0.7399331	best: 0.7402081 (1887)	total: 35m 1s	remaining: 2m 1s
1891:	learn: 0.8178621	test: 0.7401319	best: 0.7402081 (1887)	total: 35m 2s	remaining: 2m
1892:	learn: 0.8179906	test: 0.7399649	best: 0.7402081 (1887)	total: 35m 4s	remaining: 1m 58s
1893:	learn: 0.8180332	test: 0.7399821	best: 0.7402081 (1887)	total: 35m 5s	remaining: 1m 57s
1894:	learn: 0.8180765	test: 0.7400066	best: 0.7402081 (1887)	total: 35m 6s	remaining: 1m 56s
1895:	learn: 0.8182274	test: 0.7399476	best: 0.7402081 (1887)	total: 35m 7s	remaining: 1m 55s
1896:	learn: 0.8182274	test: 0.7399821	best: 0.7402081 (1887)	total: 

1974:	learn: 0.8221649	test: 0.7420745	best: 0.7421163 (1973)	total: 36m 36s	remaining: 27.8s
1975:	learn: 0.8222142	test: 0.7421409	best: 0.7421409 (1975)	total: 36m 37s	remaining: 26.7s
1976:	learn: 0.8223573	test: 0.7421409	best: 0.7421409 (1975)	total: 36m 38s	remaining: 25.6s
1977:	learn: 0.8224684	test: 0.7422072	best: 0.7422072 (1977)	total: 36m 39s	remaining: 24.5s
1978:	learn: 0.8224356	test: 0.7421997	best: 0.7422072 (1977)	total: 36m 40s	remaining: 23.4s
1979:	learn: 0.8224907	test: 0.7422072	best: 0.7422072 (1977)	total: 36m 41s	remaining: 22.2s
1980:	learn: 0.8225303	test: 0.7422660	best: 0.7422660 (1980)	total: 36m 42s	remaining: 21.1s
1981:	learn: 0.8225719	test: 0.7424820	best: 0.7424820 (1981)	total: 36m 43s	remaining: 20s
1982:	learn: 0.8225613	test: 0.7424157	best: 0.7424820 (1981)	total: 36m 44s	remaining: 18.9s
1983:	learn: 0.8226173	test: 0.7424403	best: 0.7424820 (1981)	total: 36m 46s	remaining: 17.8s
1984:	learn: 0.8226038	test: 0.7424403	best: 0.7424820 (1981)	

64:	learn: 0.7666790	test: 0.6965609	best: 0.6965609 (64)	total: 5m 13s	remaining: 2m 48s
65:	learn: 0.7671948	test: 0.6975091	best: 0.6975091 (65)	total: 5m 18s	remaining: 2m 44s
66:	learn: 0.7676344	test: 0.6972991	best: 0.6975091 (65)	total: 5m 23s	remaining: 2m 39s
67:	learn: 0.7673704	test: 0.6967751	best: 0.6975091 (65)	total: 5m 28s	remaining: 2m 34s
68:	learn: 0.7671074	test: 0.6966323	best: 0.6975091 (65)	total: 5m 33s	remaining: 2m 29s
69:	learn: 0.7679144	test: 0.6970608	best: 0.6975091 (65)	total: 5m 38s	remaining: 2m 24s
70:	learn: 0.7675989	test: 0.6963297	best: 0.6975091 (65)	total: 5m 43s	remaining: 2m 20s
71:	learn: 0.7682552	test: 0.6968951	best: 0.6975091 (65)	total: 5m 48s	remaining: 2m 15s
72:	learn: 0.7689845	test: 0.6973576	best: 0.6975091 (65)	total: 5m 53s	remaining: 2m 10s
73:	learn: 0.7698851	test: 0.6974022	best: 0.6975091 (65)	total: 5m 58s	remaining: 2m 5s
74:	learn: 0.7696168	test: 0.6979958	best: 0.6979958 (74)	total: 6m 3s	remaining: 2m 1s
75:	learn: 0.

53:	learn: 0.7419723	test: 0.6871701	best: 0.6881310 (27)	total: 3m 35s	remaining: 2h 9m 24s
54:	learn: 0.7412785	test: 0.6864309	best: 0.6881310 (27)	total: 3m 39s	remaining: 2h 9m 20s
55:	learn: 0.7408284	test: 0.6855292	best: 0.6881310 (27)	total: 3m 43s	remaining: 2h 9m 16s
56:	learn: 0.7404810	test: 0.6858213	best: 0.6881310 (27)	total: 3m 47s	remaining: 2h 9m 12s
57:	learn: 0.7409210	test: 0.6862144	best: 0.6881310 (27)	total: 3m 51s	remaining: 2h 9m 11s
58:	learn: 0.7407401	test: 0.6854044	best: 0.6881310 (27)	total: 3m 55s	remaining: 2h 9m 4s
59:	learn: 0.7396008	test: 0.6849063	best: 0.6881310 (27)	total: 3m 59s	remaining: 2h 9m
60:	learn: 0.7389314	test: 0.6849865	best: 0.6881310 (27)	total: 4m 3s	remaining: 2h 9m
61:	learn: 0.7387582	test: 0.6849744	best: 0.6881310 (27)	total: 4m 7s	remaining: 2h 8m 57s
62:	learn: 0.7397834	test: 0.6853638	best: 0.6881310 (27)	total: 4m 11s	remaining: 2h 8m 53s
63:	learn: 0.7399297	test: 0.6849623	best: 0.6881310 (27)	total: 4m 15s	remaining

142:	learn: 0.7449537	test: 0.6886240	best: 0.6888987 (137)	total: 9m 31s	remaining: 2h 3m 42s
143:	learn: 0.7451367	test: 0.6882409	best: 0.6888987 (137)	total: 9m 35s	remaining: 2h 3m 39s
144:	learn: 0.7456216	test: 0.6886519	best: 0.6888987 (137)	total: 9m 39s	remaining: 2h 3m 36s
145:	learn: 0.7456808	test: 0.6890184	best: 0.6890184 (145)	total: 9m 43s	remaining: 2h 3m 33s
146:	learn: 0.7453467	test: 0.6887268	best: 0.6890184 (145)	total: 9m 47s	remaining: 2h 3m 28s
147:	learn: 0.7453791	test: 0.6886307	best: 0.6890184 (145)	total: 9m 51s	remaining: 2h 3m 27s
148:	learn: 0.7456588	test: 0.6882263	best: 0.6890184 (145)	total: 9m 56s	remaining: 2h 3m 26s
149:	learn: 0.7459843	test: 0.6886542	best: 0.6890184 (145)	total: 10m	remaining: 2h 3m 23s
150:	learn: 0.7460211	test: 0.6887859	best: 0.6890184 (145)	total: 10m 4s	remaining: 2h 3m 22s
151:	learn: 0.7459562	test: 0.6886686	best: 0.6890184 (145)	total: 10m 8s	remaining: 2h 3m 15s
152:	learn: 0.7456660	test: 0.6889154	best: 0.6890184

228:	learn: 0.7457071	test: 0.6881493	best: 0.6894721 (162)	total: 15m 12s	remaining: 1h 57m 38s
229:	learn: 0.7457271	test: 0.6882834	best: 0.6894721 (162)	total: 15m 17s	remaining: 1h 57m 38s
230:	learn: 0.7457308	test: 0.6881471	best: 0.6894721 (162)	total: 15m 21s	remaining: 1h 57m 35s
231:	learn: 0.7458029	test: 0.6876767	best: 0.6894721 (162)	total: 15m 25s	remaining: 1h 57m 31s
232:	learn: 0.7460873	test: 0.6880790	best: 0.6894721 (162)	total: 15m 29s	remaining: 1h 57m 26s
233:	learn: 0.7459487	test: 0.6882599	best: 0.6894721 (162)	total: 15m 33s	remaining: 1h 57m 23s
234:	learn: 0.7458928	test: 0.6881046	best: 0.6894721 (162)	total: 15m 37s	remaining: 1h 57m 20s
235:	learn: 0.7462531	test: 0.6885134	best: 0.6894721 (162)	total: 15m 41s	remaining: 1h 57m 15s
236:	learn: 0.7461760	test: 0.6884710	best: 0.6894721 (162)	total: 15m 45s	remaining: 1h 57m 10s
237:	learn: 0.7461476	test: 0.6884028	best: 0.6894721 (162)	total: 15m 49s	remaining: 1h 57m 7s
238:	learn: 0.7461541	test: 0.6

313:	learn: 0.7459416	test: 0.6885726	best: 0.6894721 (162)	total: 20m 41s	remaining: 1h 51m 5s
314:	learn: 0.7462855	test: 0.6886619	best: 0.6894721 (162)	total: 20m 45s	remaining: 1h 51m 2s
315:	learn: 0.7463892	test: 0.6884107	best: 0.6894721 (162)	total: 20m 49s	remaining: 1h 50m 59s
316:	learn: 0.7461622	test: 0.6882467	best: 0.6894721 (162)	total: 20m 53s	remaining: 1h 50m 55s
317:	learn: 0.7462908	test: 0.6882891	best: 0.6894721 (162)	total: 20m 57s	remaining: 1h 50m 52s
318:	learn: 0.7459789	test: 0.6881106	best: 0.6894721 (162)	total: 21m 1s	remaining: 1h 50m 49s
319:	learn: 0.7462855	test: 0.6885469	best: 0.6894721 (162)	total: 21m 6s	remaining: 1h 50m 46s
320:	learn: 0.7462920	test: 0.6885469	best: 0.6894721 (162)	total: 21m 10s	remaining: 1h 50m 43s
321:	learn: 0.7463892	test: 0.6888125	best: 0.6894721 (162)	total: 21m 14s	remaining: 1h 50m 39s
322:	learn: 0.7463663	test: 0.6887210	best: 0.6894721 (162)	total: 21m 18s	remaining: 1h 50m 35s
323:	learn: 0.7464083	test: 0.6887

398:	learn: 0.7462137	test: 0.6883360	best: 0.6894721 (162)	total: 26m 22s	remaining: 1h 45m 51s
399:	learn: 0.7463864	test: 0.6884699	best: 0.6894721 (162)	total: 26m 27s	remaining: 1h 45m 48s
400:	learn: 0.7465061	test: 0.6884509	best: 0.6894721 (162)	total: 26m 31s	remaining: 1h 45m 44s
401:	learn: 0.7464828	test: 0.6883895	best: 0.6894721 (162)	total: 26m 35s	remaining: 1h 45m 40s
402:	learn: 0.7465536	test: 0.6887277	best: 0.6894721 (162)	total: 26m 39s	remaining: 1h 45m 37s
403:	learn: 0.7466418	test: 0.6885492	best: 0.6894721 (162)	total: 26m 43s	remaining: 1h 45m 33s
404:	learn: 0.7464778	test: 0.6883895	best: 0.6894721 (162)	total: 26m 47s	remaining: 1h 45m 29s
405:	learn: 0.7464394	test: 0.6884297	best: 0.6894721 (162)	total: 26m 51s	remaining: 1h 45m 26s
406:	learn: 0.7464803	test: 0.6886529	best: 0.6894721 (162)	total: 26m 55s	remaining: 1h 45m 23s
407:	learn: 0.7464150	test: 0.6885190	best: 0.6894721 (162)	total: 26m 59s	remaining: 1h 45m 20s
408:	learn: 0.7465707	test: 0.

483:	learn: 0.7474780	test: 0.6887323	best: 0.6894721 (162)	total: 32m 3s	remaining: 1h 40m 24s
484:	learn: 0.7473957	test: 0.6885536	best: 0.6894721 (162)	total: 32m 7s	remaining: 1h 40m 20s
485:	learn: 0.7474086	test: 0.6883515	best: 0.6894721 (162)	total: 32m 11s	remaining: 1h 40m 16s
486:	learn: 0.7472823	test: 0.6883471	best: 0.6894721 (162)	total: 32m 15s	remaining: 1h 40m 12s
487:	learn: 0.7473164	test: 0.6887277	best: 0.6894721 (162)	total: 32m 19s	remaining: 1h 40m 9s
488:	learn: 0.7475164	test: 0.6889766	best: 0.6894721 (162)	total: 32m 23s	remaining: 1h 40m 6s
489:	learn: 0.7474996	test: 0.6886150	best: 0.6894721 (162)	total: 32m 27s	remaining: 1h 40m 2s
490:	learn: 0.7474829	test: 0.6888828	best: 0.6894721 (162)	total: 32m 31s	remaining: 1h 39m 58s
491:	learn: 0.7476928	test: 0.6889789	best: 0.6894721 (162)	total: 32m 35s	remaining: 1h 39m 54s
492:	learn: 0.7475796	test: 0.6888382	best: 0.6894721 (162)	total: 32m 39s	remaining: 1h 39m 50s
493:	learn: 0.7474700	test: 0.68877

568:	learn: 0.7480245	test: 0.6892301	best: 0.6894721 (162)	total: 37m 44s	remaining: 1h 34m 53s
569:	learn: 0.7480373	test: 0.6890493	best: 0.6894721 (162)	total: 37m 48s	remaining: 1h 34m 50s
570:	learn: 0.7481299	test: 0.6891832	best: 0.6894721 (162)	total: 37m 52s	remaining: 1h 34m 46s
571:	learn: 0.7481719	test: 0.6891174	best: 0.6894721 (162)	total: 37m 56s	remaining: 1h 34m 42s
572:	learn: 0.7482333	test: 0.6894579	best: 0.6894721 (162)	total: 38m	remaining: 1h 34m 38s
573:	learn: 0.7483805	test: 0.6894837	best: 0.6894837 (573)	total: 38m 3s	remaining: 1h 34m 34s
574:	learn: 0.7484688	test: 0.6895518	best: 0.6895518 (574)	total: 38m 8s	remaining: 1h 34m 30s
575:	learn: 0.7486370	test: 0.6897585	best: 0.6897585 (575)	total: 38m 12s	remaining: 1h 34m 27s
576:	learn: 0.7486918	test: 0.6896881	best: 0.6897585 (575)	total: 38m 16s	remaining: 1h 34m 23s
577:	learn: 0.7487464	test: 0.6897797	best: 0.6897797 (577)	total: 38m 20s	remaining: 1h 34m 19s
578:	learn: 0.7486645	test: 0.689669

653:	learn: 0.7502270	test: 0.6899183	best: 0.6905549 (617)	total: 43m 27s	remaining: 1h 29m 26s
654:	learn: 0.7500694	test: 0.6899840	best: 0.6905549 (617)	total: 43m 31s	remaining: 1h 29m 23s
655:	learn: 0.7501198	test: 0.6898995	best: 0.6905549 (617)	total: 43m 35s	remaining: 1h 29m 18s
656:	learn: 0.7500841	test: 0.6900075	best: 0.6905549 (617)	total: 43m 39s	remaining: 1h 29m 14s
657:	learn: 0.7502480	test: 0.6902800	best: 0.6905549 (617)	total: 43m 43s	remaining: 1h 29m 10s
658:	learn: 0.7502817	test: 0.6903927	best: 0.6905549 (617)	total: 43m 47s	remaining: 1h 29m 6s
659:	learn: 0.7503489	test: 0.6905078	best: 0.6905549 (617)	total: 43m 51s	remaining: 1h 29m 2s
660:	learn: 0.7504434	test: 0.6902775	best: 0.6905549 (617)	total: 43m 55s	remaining: 1h 28m 58s
661:	learn: 0.7504519	test: 0.6903692	best: 0.6905549 (617)	total: 43m 59s	remaining: 1h 28m 55s
662:	learn: 0.7504056	test: 0.6905500	best: 0.6905549 (617)	total: 44m 3s	remaining: 1h 28m 51s
663:	learn: 0.7505464	test: 0.690

738:	learn: 0.7508239	test: 0.6901130	best: 0.6909376 (672)	total: 49m 1s	remaining: 1h 23m 39s
739:	learn: 0.7508197	test: 0.6901365	best: 0.6909376 (672)	total: 49m 5s	remaining: 1h 23m 35s
740:	learn: 0.7508597	test: 0.6900027	best: 0.6909376 (672)	total: 49m 9s	remaining: 1h 23m 31s
741:	learn: 0.7508598	test: 0.6900051	best: 0.6909376 (672)	total: 49m 13s	remaining: 1h 23m 27s
742:	learn: 0.7507777	test: 0.6899816	best: 0.6909376 (672)	total: 49m 17s	remaining: 1h 23m 23s
743:	learn: 0.7508092	test: 0.6897773	best: 0.6909376 (672)	total: 49m 21s	remaining: 1h 23m 18s
744:	learn: 0.7508975	test: 0.6899605	best: 0.6909376 (672)	total: 49m 24s	remaining: 1h 23m 14s
745:	learn: 0.7509121	test: 0.6898407	best: 0.6909376 (672)	total: 49m 29s	remaining: 1h 23m 10s
746:	learn: 0.7510803	test: 0.6899346	best: 0.6909376 (672)	total: 49m 33s	remaining: 1h 23m 7s
747:	learn: 0.7510236	test: 0.6898689	best: 0.6909376 (672)	total: 49m 37s	remaining: 1h 23m 3s
748:	learn: 0.7511456	test: 0.69018

824:	learn: 0.7530562	test: 0.6919673	best: 0.6919673 (824)	total: 54m 36s	remaining: 1h 17m 45s
825:	learn: 0.7530938	test: 0.6920170	best: 0.6920170 (825)	total: 54m 40s	remaining: 1h 17m 41s
826:	learn: 0.7531274	test: 0.6920144	best: 0.6920170 (825)	total: 54m 44s	remaining: 1h 17m 38s
827:	learn: 0.7531025	test: 0.6920406	best: 0.6920406 (827)	total: 54m 48s	remaining: 1h 17m 34s
828:	learn: 0.7530728	test: 0.6920170	best: 0.6920406 (827)	total: 54m 52s	remaining: 1h 17m 30s
829:	learn: 0.7531340	test: 0.6919489	best: 0.6920406 (827)	total: 54m 56s	remaining: 1h 17m 26s
830:	learn: 0.7530940	test: 0.6917447	best: 0.6920406 (827)	total: 55m	remaining: 1h 17m 22s
831:	learn: 0.7529948	test: 0.6916976	best: 0.6920406 (827)	total: 55m 4s	remaining: 1h 17m 18s
832:	learn: 0.7532116	test: 0.6918834	best: 0.6920406 (827)	total: 55m 8s	remaining: 1h 17m 14s
833:	learn: 0.7533189	test: 0.6918809	best: 0.6920406 (827)	total: 55m 12s	remaining: 1h 17m 10s
834:	learn: 0.7530958	test: 0.691878

909:	learn: 0.7550730	test: 0.6922946	best: 0.6923863 (908)	total: 1h 12s	remaining: 1h 12m 6s
910:	learn: 0.7550685	test: 0.6922264	best: 0.6923863 (908)	total: 1h 16s	remaining: 1h 12m 2s
911:	learn: 0.7551594	test: 0.6925882	best: 0.6925882 (911)	total: 1h 20s	remaining: 1h 11m 58s
912:	learn: 0.7551168	test: 0.6925829	best: 0.6925882 (911)	total: 1h 24s	remaining: 1h 11m 54s
913:	learn: 0.7552223	test: 0.6925882	best: 0.6925882 (911)	total: 1h 28s	remaining: 1h 11m 50s
914:	learn: 0.7551934	test: 0.6926826	best: 0.6926826 (914)	total: 1h 31s	remaining: 1h 11m 46s
915:	learn: 0.7552166	test: 0.6923837	best: 0.6926826 (914)	total: 1h 35s	remaining: 1h 11m 42s
916:	learn: 0.7552697	test: 0.6924807	best: 0.6926826 (914)	total: 1h 39s	remaining: 1h 11m 38s
917:	learn: 0.7553221	test: 0.6924598	best: 0.6926826 (914)	total: 1h 43s	remaining: 1h 11m 34s
918:	learn: 0.7553551	test: 0.6923890	best: 0.6926826 (914)	total: 1h 47s	remaining: 1h 11m 30s
919:	learn: 0.7553910	test: 0.6923890	best

994:	learn: 0.7560003	test: 0.6928635	best: 0.6928635 (994)	total: 1h 5m 48s	remaining: 1h 6m 28s
995:	learn: 0.7559128	test: 0.6929343	best: 0.6929343 (995)	total: 1h 5m 53s	remaining: 1h 6m 24s
996:	learn: 0.7559569	test: 0.6930025	best: 0.6930025 (996)	total: 1h 5m 57s	remaining: 1h 6m 21s
997:	learn: 0.7559005	test: 0.6928924	best: 0.6930025 (996)	total: 1h 6m 1s	remaining: 1h 6m 17s
998:	learn: 0.7559947	test: 0.6927588	best: 0.6930025 (996)	total: 1h 6m 5s	remaining: 1h 6m 13s
999:	learn: 0.7560306	test: 0.6927351	best: 0.6930025 (996)	total: 1h 6m 9s	remaining: 1h 6m 9s
1000:	learn: 0.7560157	test: 0.6927588	best: 0.6930025 (996)	total: 1h 6m 13s	remaining: 1h 6m 5s
1001:	learn: 0.7560025	test: 0.6926879	best: 0.6930025 (996)	total: 1h 6m 16s	remaining: 1h 6m 1s
1002:	learn: 0.7560766	test: 0.6928243	best: 0.6930025 (996)	total: 1h 6m 20s	remaining: 1h 5m 57s
1003:	learn: 0.7560329	test: 0.6928243	best: 0.6930025 (996)	total: 1h 6m 25s	remaining: 1h 5m 53s
1004:	learn: 0.7560366

1077:	learn: 0.7568655	test: 0.6936897	best: 0.6937732 (1069)	total: 1h 11m 21s	remaining: 1h 1m 2s
1078:	learn: 0.7568655	test: 0.6936869	best: 0.6937732 (1069)	total: 1h 11m 25s	remaining: 1h 58s
1079:	learn: 0.7568359	test: 0.6937523	best: 0.6937732 (1069)	total: 1h 11m 30s	remaining: 1h 54s
1080:	learn: 0.7568737	test: 0.6938678	best: 0.6938678 (1080)	total: 1h 11m 34s	remaining: 1h 50s
1081:	learn: 0.7569401	test: 0.6936605	best: 0.6938678 (1080)	total: 1h 11m 38s	remaining: 1h 46s
1082:	learn: 0.7569406	test: 0.6936396	best: 0.6938678 (1080)	total: 1h 11m 42s	remaining: 1h 42s
1083:	learn: 0.7568896	test: 0.6936605	best: 0.6938678 (1080)	total: 1h 11m 46s	remaining: 1h 38s
1084:	learn: 0.7569256	test: 0.6937732	best: 0.6938678 (1080)	total: 1h 11m 50s	remaining: 1h 35s
1085:	learn: 0.7569629	test: 0.6937677	best: 0.6938678 (1080)	total: 1h 11m 54s	remaining: 1h 31s
1086:	learn: 0.7570570	test: 0.6939040	best: 0.6939040 (1086)	total: 1h 11m 58s	remaining: 1h 27s
1087:	learn: 0.757

1161:	learn: 0.7571087	test: 0.6936204	best: 0.6940138 (1126)	total: 1h 16m 50s	remaining: 55m 25s
1162:	learn: 0.7572015	test: 0.6938066	best: 0.6940138 (1126)	total: 1h 16m 54s	remaining: 55m 21s
1163:	learn: 0.7573503	test: 0.6939457	best: 0.6940138 (1126)	total: 1h 16m 58s	remaining: 55m 17s
1164:	learn: 0.7573998	test: 0.6939902	best: 0.6940138 (1126)	total: 1h 17m 2s	remaining: 55m 13s
1165:	learn: 0.7572688	test: 0.6939220	best: 0.6940138 (1126)	total: 1h 17m 7s	remaining: 55m 9s
1166:	learn: 0.7572920	test: 0.6938748	best: 0.6940138 (1126)	total: 1h 17m 10s	remaining: 55m 5s
1167:	learn: 0.7574376	test: 0.6938066	best: 0.6940138 (1126)	total: 1h 17m 14s	remaining: 55m 1s
1168:	learn: 0.7573721	test: 0.6938066	best: 0.6940138 (1126)	total: 1h 17m 18s	remaining: 54m 57s
1169:	learn: 0.7574730	test: 0.6939902	best: 0.6940138 (1126)	total: 1h 17m 22s	remaining: 54m 53s
1170:	learn: 0.7574498	test: 0.6940555	best: 0.6940555 (1170)	total: 1h 17m 27s	remaining: 54m 49s
1171:	learn: 0.

1245:	learn: 0.7589792	test: 0.6949620	best: 0.6949620 (1245)	total: 1h 22m 30s	remaining: 49m 55s
1246:	learn: 0.7589502	test: 0.6950094	best: 0.6950094 (1246)	total: 1h 22m 34s	remaining: 49m 51s
1247:	learn: 0.7589989	test: 0.6948078	best: 0.6950094 (1246)	total: 1h 22m 38s	remaining: 49m 47s
1248:	learn: 0.7590448	test: 0.6948731	best: 0.6950094 (1246)	total: 1h 22m 42s	remaining: 49m 43s
1249:	learn: 0.7591184	test: 0.6950301	best: 0.6950301 (1249)	total: 1h 22m 46s	remaining: 49m 40s
1250:	learn: 0.7590720	test: 0.6950538	best: 0.6950538 (1250)	total: 1h 22m 50s	remaining: 49m 36s
1251:	learn: 0.7591259	test: 0.6949649	best: 0.6950538 (1250)	total: 1h 22m 55s	remaining: 49m 32s
1252:	learn: 0.7591434	test: 0.6949649	best: 0.6950538 (1250)	total: 1h 22m 59s	remaining: 49m 28s
1253:	learn: 0.7592194	test: 0.6952345	best: 0.6952345 (1253)	total: 1h 23m 3s	remaining: 49m 24s
1254:	learn: 0.7591840	test: 0.6952345	best: 0.6952345 (1253)	total: 1h 23m 7s	remaining: 49m 20s
1255:	learn:

1329:	learn: 0.7604914	test: 0.6958507	best: 0.6958507 (1327)	total: 1h 28m 9s	remaining: 44m 24s
1330:	learn: 0.7605546	test: 0.6958299	best: 0.6958507 (1327)	total: 1h 28m 13s	remaining: 44m 20s
1331:	learn: 0.7605042	test: 0.6959218	best: 0.6959218 (1331)	total: 1h 28m 13s	remaining: 44m 14s
1332:	learn: 0.7604819	test: 0.6958684	best: 0.6959218 (1331)	total: 1h 28m 17s	remaining: 44m 10s
1333:	learn: 0.7604803	test: 0.6956907	best: 0.6959218 (1331)	total: 1h 28m 21s	remaining: 44m 6s
1334:	learn: 0.7603753	test: 0.6957558	best: 0.6959218 (1331)	total: 1h 28m 25s	remaining: 44m 2s
1335:	learn: 0.7603313	test: 0.6959809	best: 0.6959809 (1335)	total: 1h 28m 29s	remaining: 43m 58s
1336:	learn: 0.7602993	test: 0.6960728	best: 0.6960728 (1336)	total: 1h 28m 33s	remaining: 43m 54s
1337:	learn: 0.7603794	test: 0.6961172	best: 0.6961172 (1337)	total: 1h 28m 37s	remaining: 43m 50s
1338:	learn: 0.7603985	test: 0.6960223	best: 0.6961172 (1337)	total: 1h 28m 41s	remaining: 43m 46s
1339:	learn: 

1413:	learn: 0.7616324	test: 0.6963519	best: 0.6963519 (1413)	total: 1h 33m 35s	remaining: 38m 47s
1414:	learn: 0.7615163	test: 0.6962569	best: 0.6963519 (1413)	total: 1h 33m 39s	remaining: 38m 43s
1415:	learn: 0.7615916	test: 0.6962837	best: 0.6963519 (1413)	total: 1h 33m 43s	remaining: 38m 39s
1416:	learn: 0.7616004	test: 0.6962362	best: 0.6963519 (1413)	total: 1h 33m 47s	remaining: 38m 35s
1417:	learn: 0.7616292	test: 0.6963044	best: 0.6963519 (1413)	total: 1h 33m 51s	remaining: 38m 31s
1418:	learn: 0.7616356	test: 0.6962569	best: 0.6963519 (1413)	total: 1h 33m 55s	remaining: 38m 27s
1419:	learn: 0.7616949	test: 0.6961680	best: 0.6963519 (1413)	total: 1h 33m 59s	remaining: 38m 23s
1420:	learn: 0.7618086	test: 0.6963726	best: 0.6963726 (1420)	total: 1h 34m 3s	remaining: 38m 19s
1421:	learn: 0.7617438	test: 0.6963044	best: 0.6963726 (1420)	total: 1h 34m 7s	remaining: 38m 15s
1422:	learn: 0.7617454	test: 0.6963251	best: 0.6963726 (1420)	total: 1h 34m 11s	remaining: 38m 11s
1423:	learn:

1497:	learn: 0.7627010	test: 0.6970482	best: 0.6971608 (1495)	total: 1h 39m 4s	remaining: 33m 11s
1498:	learn: 0.7626618	test: 0.6970038	best: 0.6971608 (1495)	total: 1h 39m 8s	remaining: 33m 7s
1499:	learn: 0.7626762	test: 0.6969800	best: 0.6971608 (1495)	total: 1h 39m 12s	remaining: 33m 4s
1500:	learn: 0.7626546	test: 0.6969325	best: 0.6971608 (1495)	total: 1h 39m 16s	remaining: 33m
1501:	learn: 0.7627451	test: 0.6970482	best: 0.6971608 (1495)	total: 1h 39m 20s	remaining: 32m 56s
1502:	learn: 0.7628060	test: 0.6968912	best: 0.6971608 (1495)	total: 1h 39m 24s	remaining: 32m 52s
1503:	learn: 0.7628845	test: 0.6969625	best: 0.6971608 (1495)	total: 1h 39m 28s	remaining: 32m 48s
1504:	learn: 0.7628925	test: 0.6970069	best: 0.6971608 (1495)	total: 1h 39m 32s	remaining: 32m 44s
1505:	learn: 0.7628060	test: 0.6970720	best: 0.6971608 (1495)	total: 1h 39m 36s	remaining: 32m 40s
1506:	learn: 0.7628757	test: 0.6971877	best: 0.6971877 (1506)	total: 1h 39m 40s	remaining: 32m 36s
1507:	learn: 0.762

1581:	learn: 0.7638128	test: 0.6971970	best: 0.6976205 (1565)	total: 1h 44m 39s	remaining: 27m 39s
1582:	learn: 0.7637520	test: 0.6971733	best: 0.6976205 (1565)	total: 1h 44m 43s	remaining: 27m 35s
1583:	learn: 0.7637688	test: 0.6971526	best: 0.6976205 (1565)	total: 1h 44m 47s	remaining: 27m 31s
1584:	learn: 0.7638792	test: 0.6971733	best: 0.6976205 (1565)	total: 1h 44m 51s	remaining: 27m 27s
1585:	learn: 0.7638321	test: 0.6973334	best: 0.6976205 (1565)	total: 1h 44m 55s	remaining: 27m 23s
1586:	learn: 0.7639162	test: 0.6974254	best: 0.6976205 (1565)	total: 1h 44m 58s	remaining: 27m 19s
1587:	learn: 0.7639474	test: 0.6975586	best: 0.6976205 (1565)	total: 1h 45m 2s	remaining: 27m 15s
1588:	learn: 0.7639474	test: 0.6974698	best: 0.6976205 (1565)	total: 1h 45m 6s	remaining: 27m 11s
1589:	learn: 0.7639395	test: 0.6975586	best: 0.6976205 (1565)	total: 1h 45m 10s	remaining: 27m 7s
1590:	learn: 0.7639227	test: 0.6976475	best: 0.6976475 (1590)	total: 1h 45m 14s	remaining: 27m 3s
1591:	learn: 0

1665:	learn: 0.7647242	test: 0.6983737	best: 0.6984452 (1663)	total: 1h 50m 6s	remaining: 22m 4s
1666:	learn: 0.7647474	test: 0.6984214	best: 0.6984452 (1663)	total: 1h 50m 10s	remaining: 22m
1667:	learn: 0.7647499	test: 0.6984928	best: 0.6984928 (1667)	total: 1h 50m 14s	remaining: 21m 56s
1668:	learn: 0.7648103	test: 0.6984722	best: 0.6984928 (1667)	total: 1h 50m 17s	remaining: 21m 52s
1669:	learn: 0.7647989	test: 0.6984246	best: 0.6984928 (1667)	total: 1h 50m 21s	remaining: 21m 48s
1670:	learn: 0.7647573	test: 0.6984279	best: 0.6984928 (1667)	total: 1h 50m 25s	remaining: 21m 44s
1671:	learn: 0.7647653	test: 0.6984722	best: 0.6984928 (1667)	total: 1h 50m 29s	remaining: 21m 40s
1672:	learn: 0.7649349	test: 0.6984722	best: 0.6984928 (1667)	total: 1h 50m 33s	remaining: 21m 36s
1673:	learn: 0.7649038	test: 0.6983835	best: 0.6984928 (1667)	total: 1h 50m 36s	remaining: 21m 32s
1674:	learn: 0.7649611	test: 0.6982470	best: 0.6984928 (1667)	total: 1h 50m 40s	remaining: 21m 28s
1675:	learn: 0.7

1749:	learn: 0.7658673	test: 0.6989053	best: 0.6989702 (1747)	total: 1h 55m 8s	remaining: 16m 26s
1750:	learn: 0.7658830	test: 0.6989702	best: 0.6989702 (1747)	total: 1h 55m 12s	remaining: 16m 22s
1751:	learn: 0.7659657	test: 0.6990384	best: 0.6990384 (1751)	total: 1h 55m 16s	remaining: 16m 19s
1752:	learn: 0.7659839	test: 0.6990384	best: 0.6990384 (1751)	total: 1h 55m 20s	remaining: 16m 15s
1753:	learn: 0.7660161	test: 0.6989497	best: 0.6990384 (1751)	total: 1h 55m 24s	remaining: 16m 11s
1754:	learn: 0.7659982	test: 0.6991033	best: 0.6991033 (1754)	total: 1h 55m 28s	remaining: 16m 7s
1755:	learn: 0.7661070	test: 0.6991715	best: 0.6991715 (1755)	total: 1h 55m 32s	remaining: 16m 3s
1756:	learn: 0.7660966	test: 0.6992158	best: 0.6992158 (1756)	total: 1h 55m 36s	remaining: 15m 59s
1757:	learn: 0.7660580	test: 0.6991033	best: 0.6992158 (1756)	total: 1h 55m 40s	remaining: 15m 55s
1758:	learn: 0.7661188	test: 0.6992363	best: 0.6992363 (1758)	total: 1h 55m 43s	remaining: 15m 51s
1759:	learn: 

1833:	learn: 0.7671189	test: 0.6992940	best: 0.6994409 (1798)	total: 2h 41s	remaining: 10m 55s
1834:	learn: 0.7671396	test: 0.6991166	best: 0.6994409 (1798)	total: 2h 45s	remaining: 10m 51s
1835:	learn: 0.7671668	test: 0.6992497	best: 0.6994409 (1798)	total: 2h 49s	remaining: 10m 47s
1836:	learn: 0.7671565	test: 0.6992497	best: 0.6994409 (1798)	total: 2h 52s	remaining: 10m 43s
1837:	learn: 0.7671965	test: 0.6992702	best: 0.6994409 (1798)	total: 2h 56s	remaining: 10m 39s
1838:	learn: 0.7671369	test: 0.6993384	best: 0.6994409 (1798)	total: 2h 1m	remaining: 10m 35s
1839:	learn: 0.7672080	test: 0.6993179	best: 0.6994409 (1798)	total: 2h 1m 3s	remaining: 10m 31s
1840:	learn: 0.7671926	test: 0.6992702	best: 0.6994409 (1798)	total: 2h 1m 7s	remaining: 10m 27s
1841:	learn: 0.7672212	test: 0.6990689	best: 0.6994409 (1798)	total: 2h 1m 10s	remaining: 10m 23s
1842:	learn: 0.7671721	test: 0.6991781	best: 0.6994409 (1798)	total: 2h 1m 13s	remaining: 10m 19s
1843:	learn: 0.7671786	test: 0.6992225	be

1918:	learn: 0.7686412	test: 0.6996828	best: 0.6999386 (1894)	total: 2h 5m 40s	remaining: 5m 18s
1919:	learn: 0.7686968	test: 0.6996623	best: 0.6999386 (1894)	total: 2h 5m 43s	remaining: 5m 14s
1920:	learn: 0.7687291	test: 0.6996180	best: 0.6999386 (1894)	total: 2h 5m 47s	remaining: 5m 10s
1921:	learn: 0.7687847	test: 0.6996213	best: 0.6999386 (1894)	total: 2h 5m 50s	remaining: 5m 6s
1922:	learn: 0.7688144	test: 0.6996657	best: 0.6999386 (1894)	total: 2h 5m 54s	remaining: 5m 2s
1923:	learn: 0.7687886	test: 0.6997305	best: 0.6999386 (1894)	total: 2h 5m 57s	remaining: 4m 58s
1924:	learn: 0.7688752	test: 0.6997954	best: 0.6999386 (1894)	total: 2h 6m 1s	remaining: 4m 54s
1925:	learn: 0.7689049	test: 0.6997715	best: 0.6999386 (1894)	total: 2h 6m 4s	remaining: 4m 50s
1926:	learn: 0.7688778	test: 0.6998158	best: 0.6999386 (1894)	total: 2h 6m 8s	remaining: 4m 46s
1927:	learn: 0.7689179	test: 0.6998192	best: 0.6999386 (1894)	total: 2h 6m 12s	remaining: 4m 42s
1928:	learn: 0.7689179	test: 0.6997

2:	learn: 0.7111358	test: 0.6729855	best: 0.6729855 (2)	total: 3.51s	remaining: 38m 59s
3:	learn: 0.7163844	test: 0.6751971	best: 0.6751971 (3)	total: 4.75s	remaining: 39m 32s
4:	learn: 0.7251427	test: 0.6814321	best: 0.6814321 (4)	total: 5.91s	remaining: 39m 17s
5:	learn: 0.7351543	test: 0.6861819	best: 0.6861819 (5)	total: 7.11s	remaining: 39m 22s
6:	learn: 0.7414860	test: 0.6926726	best: 0.6926726 (6)	total: 8.25s	remaining: 39m 9s
7:	learn: 0.7439657	test: 0.6950294	best: 0.6950294 (7)	total: 9.45s	remaining: 39m 14s
8:	learn: 0.7539722	test: 0.6990857	best: 0.6990857 (8)	total: 10.6s	remaining: 39m 7s
9:	learn: 0.7594928	test: 0.7013942	best: 0.7013942 (9)	total: 11.8s	remaining: 38m 59s
10:	learn: 0.7645540	test: 0.7032217	best: 0.7032217 (10)	total: 12.9s	remaining: 38m 56s
11:	learn: 0.7720875	test: 0.7066955	best: 0.7066955 (11)	total: 14.1s	remaining: 38m 51s
12:	learn: 0.7772617	test: 0.7086337	best: 0.7086337 (12)	total: 15.2s	remaining: 38m 45s
13:	learn: 0.7827137	test: 0

94:	learn: 0.9778101	test: 0.8401031	best: 0.8401031 (94)	total: 1m 50s	remaining: 36m 51s
95:	learn: 0.9785999	test: 0.8413936	best: 0.8413936 (95)	total: 1m 51s	remaining: 36m 51s
96:	learn: 0.9788741	test: 0.8418058	best: 0.8418058 (96)	total: 1m 52s	remaining: 36m 50s
97:	learn: 0.9796571	test: 0.8428591	best: 0.8428591 (97)	total: 1m 53s	remaining: 36m 49s
98:	learn: 0.9803828	test: 0.8437469	best: 0.8437469 (98)	total: 1m 54s	remaining: 36m 47s
99:	learn: 0.9807592	test: 0.8445069	best: 0.8445069 (99)	total: 1m 56s	remaining: 36m 46s
100:	learn: 0.9811134	test: 0.8448801	best: 0.8448801 (100)	total: 1m 57s	remaining: 36m 45s
101:	learn: 0.9821580	test: 0.8458220	best: 0.8458220 (101)	total: 1m 58s	remaining: 36m 44s
102:	learn: 0.9822655	test: 0.8462233	best: 0.8462233 (102)	total: 1m 59s	remaining: 36m 44s
103:	learn: 0.9829582	test: 0.8474814	best: 0.8474814 (103)	total: 2m	remaining: 36m 43s
104:	learn: 0.9831131	test: 0.8476640	best: 0.8476640 (104)	total: 2m 2s	remaining: 36

183:	learn: 0.9983707	test: 0.8794051	best: 0.8794402 (180)	total: 3m 33s	remaining: 35m 8s
184:	learn: 0.9983866	test: 0.8791371	best: 0.8794402 (180)	total: 3m 34s	remaining: 35m 7s
185:	learn: 0.9984345	test: 0.8796919	best: 0.8796919 (185)	total: 3m 35s	remaining: 35m 6s
186:	learn: 0.9984823	test: 0.8803402	best: 0.8803402 (186)	total: 3m 37s	remaining: 35m 5s
187:	learn: 0.9985143	test: 0.8802517	best: 0.8803402 (186)	total: 3m 38s	remaining: 35m 4s
188:	learn: 0.9985622	test: 0.8806215	best: 0.8806215 (188)	total: 3m 39s	remaining: 35m 3s
189:	learn: 0.9986499	test: 0.8811119	best: 0.8811119 (189)	total: 3m 40s	remaining: 35m 1s
190:	learn: 0.9986420	test: 0.8805975	best: 0.8811119 (189)	total: 3m 41s	remaining: 35m
191:	learn: 0.9986579	test: 0.8812050	best: 0.8812050 (191)	total: 3m 42s	remaining: 34m 59s
192:	learn: 0.9987377	test: 0.8812232	best: 0.8812232 (192)	total: 3m 44s	remaining: 34m 58s
193:	learn: 0.9988335	test: 0.8804956	best: 0.8812232 (192)	total: 3m 45s	remaini

272:	learn: 0.9999040	test: 0.8897473	best: 0.8897473 (272)	total: 5m 14s	remaining: 33m 11s
273:	learn: 0.9999040	test: 0.8894660	best: 0.8897473 (272)	total: 5m 16s	remaining: 33m 10s
274:	learn: 0.9999120	test: 0.8895771	best: 0.8897473 (272)	total: 5m 17s	remaining: 33m 9s
275:	learn: 0.9999040	test: 0.8889999	best: 0.8897473 (272)	total: 5m 18s	remaining: 33m 8s
276:	learn: 0.9999200	test: 0.8890740	best: 0.8897473 (272)	total: 5m 19s	remaining: 33m 7s
277:	learn: 0.9999200	test: 0.8895399	best: 0.8897473 (272)	total: 5m 20s	remaining: 33m 6s
278:	learn: 0.9999200	test: 0.8895399	best: 0.8897473 (272)	total: 5m 21s	remaining: 33m 5s
279:	learn: 0.9999280	test: 0.8895103	best: 0.8897473 (272)	total: 5m 23s	remaining: 33m 4s
280:	learn: 0.9999200	test: 0.8899241	best: 0.8899241 (280)	total: 5m 24s	remaining: 33m 2s
281:	learn: 0.9999120	test: 0.8900346	best: 0.8900346 (281)	total: 5m 25s	remaining: 33m 1s
282:	learn: 0.9999120	test: 0.8899537	best: 0.8900346 (281)	total: 5m 26s	rema

361:	learn: 1.0000000	test: 0.8931794	best: 0.8935479 (360)	total: 6m 55s	remaining: 31m 18s
362:	learn: 1.0000000	test: 0.8933037	best: 0.8935479 (360)	total: 6m 56s	remaining: 31m 17s
363:	learn: 1.0000000	test: 0.8933179	best: 0.8935479 (360)	total: 6m 57s	remaining: 31m 16s
364:	learn: 1.0000000	test: 0.8937581	best: 0.8937581 (364)	total: 6m 58s	remaining: 31m 15s
365:	learn: 1.0000000	test: 0.8935013	best: 0.8937581 (364)	total: 6m 59s	remaining: 31m 14s
366:	learn: 1.0000000	test: 0.8934731	best: 0.8937581 (364)	total: 7m 1s	remaining: 31m 13s
367:	learn: 1.0000000	test: 0.8933997	best: 0.8937581 (364)	total: 7m 2s	remaining: 31m 12s
368:	learn: 1.0000000	test: 0.8936565	best: 0.8937581 (364)	total: 7m 3s	remaining: 31m 11s
369:	learn: 1.0000000	test: 0.8938696	best: 0.8938696 (369)	total: 7m 4s	remaining: 31m 10s
370:	learn: 1.0000000	test: 0.8934731	best: 0.8938696 (369)	total: 7m 5s	remaining: 31m 9s
371:	learn: 1.0000000	test: 0.8934872	best: 0.8938696 (369)	total: 7m 6s	rem

450:	learn: 1.0000000	test: 0.8948082	best: 0.8948082 (450)	total: 8m 35s	remaining: 29m 31s
451:	learn: 1.0000000	test: 0.8944198	best: 0.8948082 (450)	total: 8m 36s	remaining: 29m 30s
452:	learn: 1.0000000	test: 0.8945226	best: 0.8948082 (450)	total: 8m 37s	remaining: 29m 28s
453:	learn: 1.0000000	test: 0.8945818	best: 0.8948082 (450)	total: 8m 39s	remaining: 29m 27s
454:	learn: 1.0000000	test: 0.8947508	best: 0.8948082 (450)	total: 8m 40s	remaining: 29m 26s
455:	learn: 1.0000000	test: 0.8948692	best: 0.8948692 (455)	total: 8m 41s	remaining: 29m 25s
456:	learn: 1.0000000	test: 0.8947351	best: 0.8948692 (455)	total: 8m 42s	remaining: 29m 24s
457:	learn: 1.0000000	test: 0.8948291	best: 0.8948692 (455)	total: 8m 43s	remaining: 29m 23s
458:	learn: 1.0000000	test: 0.8951146	best: 0.8951146 (458)	total: 8m 44s	remaining: 29m 22s
459:	learn: 1.0000000	test: 0.8952312	best: 0.8952312 (459)	total: 8m 46s	remaining: 29m 21s
460:	learn: 1.0000000	test: 0.8952173	best: 0.8952312 (459)	total: 8m 

539:	learn: 1.0000000	test: 0.8972869	best: 0.8973284 (523)	total: 10m 22s	remaining: 28m 2s
540:	learn: 1.0000000	test: 0.8973005	best: 0.8973284 (523)	total: 10m 23s	remaining: 28m 2s
541:	learn: 1.0000000	test: 0.8971161	best: 0.8973284 (523)	total: 10m 25s	remaining: 28m 1s
542:	learn: 1.0000000	test: 0.8974207	best: 0.8974207 (542)	total: 10m 26s	remaining: 28m
543:	learn: 1.0000000	test: 0.8972252	best: 0.8974207 (542)	total: 10m 27s	remaining: 27m 59s
544:	learn: 1.0000000	test: 0.8972980	best: 0.8974207 (542)	total: 10m 28s	remaining: 27m 58s
545:	learn: 1.0000000	test: 0.8972481	best: 0.8974207 (542)	total: 10m 29s	remaining: 27m 57s
546:	learn: 1.0000000	test: 0.8973208	best: 0.8974207 (542)	total: 10m 31s	remaining: 27m 56s
547:	learn: 1.0000000	test: 0.8973369	best: 0.8974207 (542)	total: 10m 32s	remaining: 27m 55s
548:	learn: 1.0000000	test: 0.8970729	best: 0.8974207 (542)	total: 10m 33s	remaining: 27m 54s
549:	learn: 1.0000000	test: 0.8974232	best: 0.8974232 (549)	total: 

627:	learn: 1.0000000	test: 0.8994270	best: 0.8997991 (621)	total: 12m 5s	remaining: 26m 24s
628:	learn: 1.0000000	test: 0.8994929	best: 0.8997991 (621)	total: 12m 6s	remaining: 26m 23s
629:	learn: 1.0000000	test: 0.8993182	best: 0.8997991 (621)	total: 12m 7s	remaining: 26m 22s
630:	learn: 1.0000000	test: 0.8993611	best: 0.8997991 (621)	total: 12m 8s	remaining: 26m 21s
631:	learn: 1.0000000	test: 0.8992687	best: 0.8997991 (621)	total: 12m 10s	remaining: 26m 20s
632:	learn: 1.0000000	test: 0.8993412	best: 0.8997991 (621)	total: 12m 11s	remaining: 26m 19s
633:	learn: 1.0000000	test: 0.8991303	best: 0.8997991 (621)	total: 12m 12s	remaining: 26m 18s
634:	learn: 1.0000000	test: 0.8990511	best: 0.8997991 (621)	total: 12m 13s	remaining: 26m 17s
635:	learn: 1.0000000	test: 0.8991436	best: 0.8997991 (621)	total: 12m 14s	remaining: 26m 16s
636:	learn: 1.0000000	test: 0.8992294	best: 0.8997991 (621)	total: 12m 16s	remaining: 26m 14s
637:	learn: 1.0000000	test: 0.8991865	best: 0.8997991 (621)	tota

715:	learn: 1.0000000	test: 0.9006052	best: 0.9008221 (695)	total: 13m 46s	remaining: 24m 41s
716:	learn: 1.0000000	test: 0.9007498	best: 0.9008221 (695)	total: 13m 47s	remaining: 24m 40s
717:	learn: 1.0000000	test: 0.9007071	best: 0.9008221 (695)	total: 13m 48s	remaining: 24m 39s
718:	learn: 1.0000000	test: 0.9007729	best: 0.9008221 (695)	total: 13m 49s	remaining: 24m 38s
719:	learn: 1.0000000	test: 0.9009211	best: 0.9009211 (719)	total: 13m 50s	remaining: 24m 37s
720:	learn: 1.0000000	test: 0.9010230	best: 0.9010230 (720)	total: 13m 52s	remaining: 24m 35s
721:	learn: 1.0000000	test: 0.9010888	best: 0.9010888 (721)	total: 13m 53s	remaining: 24m 34s
722:	learn: 1.0000000	test: 0.9008061	best: 0.9010888 (721)	total: 13m 54s	remaining: 24m 33s
723:	learn: 1.0000000	test: 0.9008061	best: 0.9010888 (721)	total: 13m 54s	remaining: 24m 31s
724:	learn: 1.0000000	test: 0.9007337	best: 0.9010888 (721)	total: 13m 56s	remaining: 24m 30s
725:	learn: 1.0000000	test: 0.9008914	best: 0.9010888 (721)	

KeyboardInterrupt: 

In [5]:
categorical_features_indices = np.where(X_trainC.dtypes == "object")[0]
CATboost = CatBoostClassifier(eval_metric = "F1", random_seed = 42, verbose = False, auto_class_weights = "Balanced",
                              iterations = 200, learning_rate = 0.001, depth = 5, l2_leaf_reg = 5)
                             
CATboost.fit(X_trainC, Y_trainC, cat_features = categorical_features_indices, eval_set=(X_testC, Y_testC), plot=True)

Custom logger is already specified. Specify more than one logger at same time is not thread safe.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [7]:
print(CATboost.score(X_trainC, Y_trainC), CATboost.score(X_testC, Y_testC))
# X_trainC, X_testC, Y_trainC, Y_testC

0.9846537250786989 0.9841177797107052


In [8]:
confusion_matrix(Y_trainC, CATboost.predict(X_trainC))

array([[ 27485,    425],
       [  1798, 115148]])

In [10]:
27485/(27485+ 425)

0.9847724829810104